# 라이브러리

In [141]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

import warnings
warnings.filterwarnings(action = 'ignore')

In [142]:
import matplotlib.font_manager as fm
fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font = fm.FontProperties(fname=fontpath, size=9)
plt.rc('font', family='NanumBarunGothic') 
mpl.font_manager._rebuild()

In [143]:
#한글
plt.rc('font', family='Malgun Gothic')
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')

In [144]:
datas = pd.read_csv('data/train_data_04.csv')

In [145]:
data = datas.copy()

# 데이터 전처리

In [146]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [147]:
data['방송일시'] = pd.to_datetime(data['방송일시'])
data['방송시간'] = data['방송일시'].dt.hour
data['방송요일'] = data['방송일시'].dt.day_name()

In [148]:
data['방송시간'] = data['방송시간'].astype('object')

In [149]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35379 entries, 0 to 35378
Data columns (total 22 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   방송일시     35379 non-null  datetime64[ns]
 1   노출(분)    35379 non-null  float64
 2   마더코드     35379 non-null  int64
 3   상품코드     35379 non-null  int64
 4   상품명      35379 non-null  object
 5   상품군      35379 non-null  object
 6   판매단가     35379 non-null  int64
 7   취급액      35379 non-null  float64
 8   세부상품군    35379 non-null  object
 9   브랜드      35379 non-null  object
 10  시청률      35379 non-null  float64
 11  건수       35379 non-null  float64
 12  방송날짜     35379 non-null  object
 13  방송월      35379 non-null  int64
 14  방송일      35379 non-null  int64
 15  방송요일     35379 non-null  object
 16  방송시간     35379 non-null  object
 17  평일/주말    35379 non-null  int64
 18  공휴일      35379 non-null  int64
 19  계절       35379 non-null  object
 20  방송회차     35379 non-null  int64
 21  무이자/일시불  12548 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(8), object(9)
memory usage: 5.9+ MB

In [150]:
data["방송시간"] = data["방송시간"].map(str) + "시"

In [151]:
data

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,세부상품군,브랜드,...,방송날짜,방송월,방송일,방송요일,방송시간,평일/주말,공휴일,계절,방송회차,무이자/일시불
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,니트/터틀넥/기모,테이트,...,2019-01-01,1,1,Tuesday,6시,0,1,겨울,1,NaN
1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,니트/터틀넥/기모,테이트,...,2019-01-01,1,1,Tuesday,6시,0,1,겨울,1,NaN
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,니트/터틀넥/기모,테이트,...,2019-01-01,1,1,Tuesday,6시,0,1,겨울,2,NaN
3,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,니트/터틀넥/기모,테이트,...,2019-01-01,1,1,Tuesday,6시,0,1,겨울,2,NaN
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0,니트/터틀넥/기모,테이트,...,2019-01-01,1,1,Tuesday,6시,0,1,겨울,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0,밥솥,쿠첸,...,2019-12-31,12,31,Tuesday,23시,0,0,겨울,2,일시불
35375,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000.0,밥솥,쿠첸,...,2020-01-01,1,1,Wednesday,0시,0,1,겨울,3,무이자
35376,2020-01-01 00:00:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000.0,밥솥,쿠첸,...,2020-01-01,1,1,Wednesday,0시,0,1,겨울,3,일시불
35377,2020-01-01 00:00:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000.0,밥솥,쿠첸,...,2020-01-01,1,1,Wednesday,0시,0,1,겨울,3,무이자
35378,2020-01-01 00:00:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000.0,밥솥,쿠첸,...,2020-01-01,1,1,Wednesday,0시,0,1,겨울,3,일시불

In [152]:
apriori_data = data[['방송일시','방송시간','방송요일','상품군']]

In [153]:
df = apriori_data.astype('object')

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35379 entries, 0 to 35378
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   방송일시    35379 non-null  object
 1   방송시간    35379 non-null  object
 2   방송요일    35379 non-null  object
 3   상품군     35379 non-null  object
dtypes: object(4)
memory usage: 1.1+ MB

In [155]:
#중복된 데이터 제거
df = df.drop_duplicates()

In [156]:
df.drop('방송일시',axis=1,inplace=True)

In [157]:
df

      방송시간       방송요일 상품군
0       6시    Tuesday  의류
2       6시    Tuesday  의류
4       6시    Tuesday  의류
6       7시    Tuesday  속옷
7       7시    Tuesday  속옷
...    ...        ...  ..
35363  21시    Tuesday  가전
35365  22시    Tuesday  가전
35367  23시    Tuesday  주방
35371  23시    Tuesday  주방
35375   0시  Wednesday  주방

[20566 rows x 3 columns]

In [158]:
df_val = df.values  #array로 가능(Dataframe불가)

In [159]:
df_val

array([['6시', 'Tuesday', '의류'],
       ['6시', 'Tuesday', '의류'],
       ['6시', 'Tuesday', '의류'],
       ...,
       ['23시', 'Tuesday', '주방'],
       ['23시', 'Tuesday', '주방'],
       ['0시', 'Wednesday', '주방']], dtype=object)

In [160]:
len(df_val)

20566

# 연관성분석(장바구니분석)

In [161]:
te = TransactionEncoder()
te_ary = te.fit(df_val).transform(df_val)
dataset = pd.DataFrame(te_ary, columns=te.columns_)

In [162]:
dataset

,0시,10시,11시,12시,13시,14시,15시,16시,17시,18시,...,가전,건강기능,농수축,생활용품,속옷,의류,이미용,잡화,주방,침구
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20561,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
20562,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
20563,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
20564,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
20565,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [163]:
frequent_itemsets = apriori(dataset, min_support=0.001, use_colnames=True) #총 1672개 조합

In [164]:
frequent_itemsets

      support             itemsets
0    0.039337                 (0시)
1    0.052028                (10시)
2    0.051784                (11시)
3    0.049451                (12시)
4    0.051104                (13시)
..        ...                  ...
774  0.001702    (주방, 9시, Tuesday)
775  0.001118  (속옷, 9시, Wednesday)
776  0.002334  (의류, 9시, Wednesday)
777  0.001070  (잡화, 9시, Wednesday)
778  0.001605  (9시, 주방, Wednesday)

[779 rows x 2 columns]

In [165]:
combin = []
for i in range(len(frequent_itemsets)):
    if len(frequent_itemsets.iloc[i][1]) == 3:
        combin.append(sorted(list(frequent_itemsets.iloc[i][1])))

In [166]:
len(combin)

370

In [167]:
combindata = pd.DataFrame(combin, columns=['방송시간','방송요일','상품군'])
combindata.tail(30)

    방송시간       방송요일 상품군
340   8시    Tuesday  속옷
341   8시    Tuesday  의류
342   8시    Tuesday  잡화
343   8시    Tuesday  주방
344   8시  Wednesday  속옷
345   8시  Wednesday  의류
346   8시  Wednesday  주방
347   9시     Friday  의류
348   9시     Friday  잡화
349   9시     Friday  주방
350   9시     Monday  의류
351   9시     Monday  잡화
352   9시     Monday  주방
353   9시   Saturday  의류
354   9시   Saturday  잡화
355   9시   Saturday  주방
356   9시     Sunday  의류
357   9시     Sunday  잡화
358   9시     Sunday  주방
359   9시   Thursday  의류
360   9시   Thursday  잡화
361   9시   Thursday  주방
362   9시    Tuesday  속옷
363   9시    Tuesday  의류
364   9시    Tuesday  잡화
365   9시    Tuesday  주방
366   9시  Wednesday  속옷
367   9시  Wednesday  의류
368   9시  Wednesday  잡화
369   9시  Wednesday  주방

In [168]:
combindata['상품군'].value_counts()

주방      74
의류      73
속옷      67
농수축     53
잡화      38
가전      26
생활용품    14
이미용     10
가구       9
건강기능     6
Name: 상품군, dtype: int64

In [169]:
combindata[combindata['상품군']=='건강기능']

    방송시간       방송요일   상품군
284   6시     Monday  건강기능
301   7시     Friday  건강기능
311   7시     Sunday  건강기능
314   7시   Thursday  건강기능
317   7시    Tuesday  건강기능
322   7시  Wednesday  건강기능

In [170]:
combindata[combindata['상품군']=='가구']

    방송시간       방송요일 상품군
240  21시     Friday  가구
245  21시     Sunday  가구
247  21시   Thursday  가구
249  21시    Tuesday  가구
251  21시  Wednesday  가구
254  22시     Monday  가구
258  22시   Saturday  가구
262  22시    Tuesday  가구
278  23시  Wednesday  가구

In [171]:
combindata[combindata['상품군']=='농수축']

    방송시간       방송요일  상품군
17   10시     Friday  농수축
20   10시     Monday  농수축
31   10시   Thursday  농수축
33   10시    Tuesday  농수축
37   10시  Wednesday  농수축
40   11시     Friday  농수축
44   11시     Monday  농수축
48   11시   Saturday  농수축
53   11시     Sunday  농수축
57   11시   Thursday  농수축
61   11시    Tuesday  농수축
64   11시  Wednesday  농수축
67   12시     Friday  농수축
70   12시     Monday  농수축
80   12시    Tuesday  농수축
82   12시  Wednesday  농수축
86   13시     Monday  농수축
89   13시   Saturday  농수축
100  13시  Wednesday  농수축
105  14시     Monday  농수축
122  14시  Wednesday  농수축
125  15시     Friday  농수축
128  15시     Monday  농수축
131  15시   Saturday  농수축
135  15시     Sunday  농수축
138  15시   Thursday  농수축
141  15시    Tuesday  농수축
144  15시  Wednesday  농수축
147  16시     Friday  농수축
148  16시     Monday  농수축
149  16시   Saturday  농수축
151  16시     Sunday  농수축
154  16시   Thursday  농수축
155  16시    Tuesday  농수축
157  16시  Wednesday  농수축
159  17시     Friday  농수축
161  17시     Monday  농수축
163  17시   Saturday  농수축
164  17시     Sunday  농수축
166  17시   Thursday  농수축
167  17시    Tuesday  농수축
169  17시  Wednesday  농수축
171  18시     Friday  농수축
173  18시     Monday  농수축
175  18시     Sunday  농수축
176  18시   Thursday  농수축
178  18시    Tuesday  농수축
180  18시  Wednesday  농수축
186  19시   Saturday  농수축
204   1시   Saturday  농수축
208   1시     Sunday  농수축
226  20시   Saturday  농수축
234  20시    Tuesday  농수축

In [172]:
combindata[combindata['상품군']=='가전']

    방송시간       방송요일 상품군
27   10시     Sunday  가전
75   12시     Sunday  가전
220  20시     Friday  가전
223  20시     Monday  가전
227  20시     Sunday  가전
233  20시    Tuesday  가전
237  20시  Wednesday  가전
241  21시     Friday  가전
242  21시     Monday  가전
244  21시   Saturday  가전
246  21시     Sunday  가전
248  21시   Thursday  가전
250  21시    Tuesday  가전
252  21시  Wednesday  가전
253  22시     Friday  가전
255  22시     Monday  가전
259  22시   Saturday  가전
260  22시     Sunday  가전
261  22시   Thursday  가전
263  22시    Tuesday  가전
264  22시  Wednesday  가전
265  23시     Monday  가전
269  23시   Saturday  가전
272  23시     Sunday  가전
275  23시   Thursday  가전
276  23시    Tuesday  가전

In [173]:
combin

[['0시', 'Friday', '생활용품'],
 ['0시', 'Friday', '속옷'],
 ['0시', 'Friday', '의류'],
 ['0시', 'Monday', '생활용품'],
 ['0시', 'Monday', '속옷'],
 ['0시', 'Monday', '의류'],
 ['0시', 'Saturday', '의류'],
 ['0시', 'Sunday', '속옷'],
 ['0시', 'Thursday', '속옷'],
 ['0시', 'Thursday', '의류'],
 ['0시', 'Thursday', '잡화'],
 ['0시', 'Tuesday', '속옷'],
 ['0시', 'Tuesday', '의류'],
 ['0시', 'Wednesday', '생활용품'],
 ['0시', 'Wednesday', '속옷'],
 ['0시', 'Wednesday', '의류'],
 ['0시', 'Wednesday', '잡화'],
 ['10시', 'Friday', '농수축'],
 ['10시', 'Friday', '의류'],
 ['10시', 'Friday', '주방'],
 ['10시', 'Monday', '농수축'],
 ['10시', 'Monday', '속옷'],
 ['10시', 'Monday', '의류'],
 ['10시', 'Monday', '잡화'],
 ['10시', 'Monday', '주방'],
 ['10시', 'Saturday', '의류'],
 ['10시', 'Saturday', '잡화'],
 ['10시', 'Sunday', '가전'],
 ['10시', 'Sunday', '의류'],
 ['10시', 'Sunday', '잡화'],
 ['10시', 'Sunday', '주방'],
 ['10시', 'Thursday', '농수축'],
 ['10시', 'Thursday', '주방'],
 ['10시', 'Tuesday', '농수축'],
 ['10시', 'Tuesday', '의류'],
 ['10시', 'Tuesday', '잡화'],
 ['10시', 'Tuesday', '주방'],
 ['10시', 'Wednesday', '농수축'],
 ['10시', 'Wednesday', '속옷'],
 ['10시', 'Wednesday', '주방'],
 ['11시', 'Friday', '농수축'],
 ['11시', 'Friday', '의류'],
 ['11시', 'Friday', '잡화'],
 ['11시', 'Friday', '주방'],
 ['11시', 'Monday', '농수축'],
 ['11시', 'Monday', '속옷'],
 ['11시', 'Monday', '의류'],
 ['11시', 'Monday', '주방'],
 ['11시', 'Saturday', '농수축'],
 ['11시', 'Saturday', '속옷'],
 ['11시', 'Saturday', '의류'],
 ['11시', 'Saturday', '잡화'],
 ['11시', 'Saturday', '주방'],
 ['11시', 'Sunday', '농수축'],
 ['11시', 'Sunday', '속옷'],
 ['11시', 'Sunday', '의류'],
 ['11시', 'Sunday', '잡화'],
 ['11시', 'Thursday', '농수축'],
 ['11시', 'Thursday', '속옷'],
 ['11시', 'Thursday', '의류'],
 ['11시', 'Thursday', '잡화'],
 ['11시', 'Tuesday', '농수축'],
 ['11시', 'Tuesday', '의류'],
 ['11시', 'Tuesday', '주방'],
 ['11시', 'Wednesday', '농수축'],
 ['11시', 'Wednesday', '의류'],
 ['11시', 'Wednesday', '주방'],
 ['12시', 'Friday', '농수축'],
 ['12시', 'Friday', '잡화'],
 ['12시', 'Friday', '주방'],
 ['12시', 'Monday', '농수축'],
 ['12시', 'Monday', '주방'],
 ['12시', 'Saturday', '의류'],
 ['12시', 'Saturday', '이미용'],
 ['12시', 'Saturday', '주방'],
 ['12시', 'Sunday', '가전'],
 ['12시', 'Sunday', '의류'],
 ['12시', 'Sunday', '주방'],
 ['12시', 'Thursday', '잡화'],
 ['12시', 'Thursday', '주방'],
 ['12시', 'Tuesday', '농수축'],
 ['12시', 'Tuesday', '주방'],
 ['12시', 'Wednesday', '농수축'],
 ['12시', 'Wednesday', '생활용품'],
 ['12시', 'Wednesday', '주방'],
 ['13시', 'Friday', '주방'],
 ['13시', 'Monday', '농수축'],
 ['13시', 'Monday', '의류'],
 ['13시', 'Monday', '주방'],
 ['13시', 'Saturday', '농수축'],
 ['13시', 'Saturday', '의류'],
 ['13시', 'Saturday', '이미용'],
 ['13시', 'Saturday', '잡화'],
 ['13시', 'Sunday', '잡화'],
 ['13시', 'Sunday', '주방'],
 ['13시', 'Thursday', '잡화'],
 ['13시', 'Thursday', '주방'],
 ['13시', 'Tuesday', '속옷'],
 ['13시', 'Tuesday', '잡화'],
 ['13시', 'Tuesday', '주방'],
 ['13시', 'Wednesday', '농수축'],
 ['13시', 'Wednesday', '의류'],
 ['13시', 'Wednesday', '주방'],
 ['14시', 'Friday', '속옷'],
 ['14시', 'Friday', '의류'],
 ['14시', 'Monday', '농수축'],
 ['14시', 'Monday', '속옷'],
 ['14시', 'Monday', '잡화'],
 ['14시', 'Monday', '주방'],
 ['14시', 'Saturday', '속옷'],
 ['14시', 'Saturday', '의류'],
 ['14시', 'Saturday', '주방'],
 ['14시', 'Sunday', '속옷'],
 ['14시', 'Sunday', '의류'],
 ['14시', 'Sunday', '이미용'],
 ['14시', 'Sunday', '주방'],
 ['14시', 'Thursday', '속옷'],
 ['14시', 'Thursday', '의류'],
 ['14시', 'Thursday', '주방'],
 ['14시', 'Tuesday', '속옷'],
 ['14시', 'Tuesday', '의류'],
 ['14시', 'Tuesday', '주방'],
 ['14시', 'Wednesday', '농수축'],
 ['14시', 'Wednesday', '속옷'],
 ['14시', 'Wednesday', '주방'],
 ['15시', 'Friday', '농수축'],
 ['15시', 'Friday', '속옷'],
 ['15시', 'Friday', '주방'],
 ['15시', 'Monday', '농수축'],
 ['15시', 'Monday', '속옷'],
 ['15시', 'Monday', '주방'],
 ['15시', 'Saturday', '농수축'],
 ['15시', 'Saturday', '속옷'],
 ['15시', 'Saturday', '의류'],
 ['15시', 'Saturday', '주방'],
 ['15시', 'Sunday', '농수축'],
 ['15시', 'Sunday', '의류'],
 ['15시', 'Sunday', '주방'],
 ['15시', 'Thursday', '농수축'],
 ['15시', 'Thursday', '속옷'],
 ['15시', 'Thursday', '주방'],
 ['15시', 'Tuesday', '농수축'],
 ['15시', 'Tuesday', '속옷'],
 ['15시', 'Tuesday', '주방'],
 ['15시', 'Wednesday', '농수축'],
 ['15시', 'Wednesday', '속옷'],
 ['15시', 'Wednesday', '주방'],
 ['16시', 'Friday', '농수축'],
 ['16시', 'Monday', '농수축'],
 ['16시', 'Saturday', '농수축'],
 ['16시', 'Saturday', '주방'],
 ['16시', 'Sunday', '농수축'],
 ['16시', 'Sunday', '이미용'],
 ['16시', 'Sunday', '주방'],
 ['16시', 'Thursday', '농수축'],
 ['16시', 'Tuesday', '농수축'],
 ['16시', 'Tuesday', '주방'],
 ['16시', 'Wednesday', '농수축'],
 ['16시', 'Wednesday', '주방'],
 ['17시', 'Friday', '농수축'],
 ['17시', 'Friday', '주방'],
 ['17시', 'Monday', '농수축'],
 ['17시', 'Monday', '주방'],
 ['17시', 'Saturday', '농수축'],
 ['17시', 'Sunday', '농수축'],
 ['17시', 'Sunday', '주방'],
 ['17시', 'Thursday', '농수축'],
 ['17시', 'Tuesday', '농수축'],
 ['17시', 'Tuesday', '주방'],
 ['17시', 'Wednesday', '농수축'],
 ['17시', 'Wednesday', '주방'],
 ['18시', 'Friday', '농수축'],
 ['18시', 'Friday', '주방'],
 ['18시', 'Monday', '농수축'],
 ['18시', 'Monday', '주방'],
 ['18시', 'Sunday', '농수축'],
 ['18시', 'Thursday', '농수축'],
 ['18시', 'Thursday', '주방'],
 ['18시', 'Tuesday', '농수축'],
 ['18시', 'Tuesday', '주방'],
 ['18시', 'Wednesday', '농수축'],
 ['19시', 'Friday', '속옷'],
 ['19시', 'Friday', '의류'],
 ['19시', 'Monday', '속옷'],
 ['19시', 'Monday', '의류'],
 ['19시', 'Monday', '이미용'],
 ['19시', 'Saturday', '농수축'],
 ['19시', 'Saturday', '주방'],
 ['19시', 'Sunday', '속옷'],
 ['19시', 'Thursday', '생활용품'],
 ['19시', 'Thursday', '속옷'],
 ['19시', 'Tuesday', '속옷'],
 ['19시', 'Tuesday', '주방'],
 ['19시', 'Wednesday', '속옷'],
 ['19시', 'Wednesday', '의류'],
 ['19시', 'Wednesday', '주방'],
 ['1시', 'Friday', '속옷'],
 ['1시', 'Friday', '이미용'],
 ['1시', 'Friday', '잡화'],
 ['1시', 'Monday', '생활용품'],
 ['1시', 'Monday', '속옷'],
 ['1시', 'Monday', '의류'],
 ['1시', 'Monday', '이미용'],
 ['1시', 'Monday', '잡화'],
 ['1시', 'Saturday', '농수축'],
 ['1시', 'Saturday', '속옷'],
 ['1시', 'Saturday', '의류'],
 ['1시', 'Saturday', '잡화'],
 ['1시', 'Sunday', '농수축'],
 ['1시', 'Sunday', '속옷'],
 ['1시', 'Sunday', '의류'],
 ['1시', 'Thursday', '속옷'],
 ['1시', 'Tuesday', '생활용품'],
 ['1시', 'Tuesday', '속옷'],
 ['1시', 'Tuesday', '의류'],
 ['1시', 'Tuesday', '이미용'],
 ['1시', 'Tuesday', '잡화'],
 ['1시', 'Wednesday', '속옷'],
 ['1시', 'Wednesday', '의류'],
 ['1시', 'Wednesday', '잡화'],
 ['20시', 'Friday', '가전'],
 ['20시', 'Friday', '속옷'],
 ['20시', 'Friday', '주방'],
 ['20시', 'Monday', '가전'],
 ['20시', 'Monday', '속옷'],
 ['20시', 'Monday', '주방'],
 ['20시', 'Saturday', '농수축'],
 ['20시', 'Sunday', '가전'],
 ['20시', 'Sunday', '속옷'],
 ['20시', 'Sunday', '의류'],
 ['20시', 'Thursday', '생활용품'],
 ['20시', 'Thursday', '속옷'],
 ['20시', 'Thursday', '의류'],
 ['20시', 'Tuesday', '가전'],
 ['20시', 'Tuesday', '농수축'],
 ['20시', 'Tuesday', '의류'],
 ['20시', 'Tuesday', '주방'],
 ['20시', 'Wednesday', '가전'],
 ['20시', 'Wednesday', '속옷'],
 ['20시', 'Wednesday', '의류'],
 ['21시', 'Friday', '가구'],
 ['21시', 'Friday', '가전'],
 ['21시', 'Monday', '가전'],
 ['21시', 'Monday', '주방'],
 ['21시', 'Saturday', '가전'],
 ['21시', 'Sunday', '가구'],
 ['21시', 'Sunday', '가전'],
 ['21시', 'Thursday', '가구'],
 ['21시', 'Thursday', '가전'],
 ['21시', 'Tuesday', '가구'],
 ['21시', 'Tuesday', '가전'],
 ['21시', 'Wednesday', '가구'],
 ['21시', 'Wednesday', '가전'],
 ['22시', 'Friday', '가전'],
 ['22시', 'Monday', '가구'],
 ['22시', 'Monday', '가전'],
 ['22시', 'Monday', '속옷'],
 ['22시', 'Monday', '주방'],
 ['22시', 'Saturday', '가구'],
 ['22시', 'Saturday', '가전'],
 ['22시', 'Sunday', '가전'],
 ['22시', 'Thursday', '가전'],
 ['22시', 'Tuesday', '가구'],
 ['22시', 'Tuesday', '가전'],
 ['22시', 'Wednesday', '가전'],
 ['23시', 'Monday', '가전'],
 ['23시', 'Monday', '생활용품'],
 ['23시', 'Monday', '속옷'],
 ['23시', 'Monday', '의류'],
 ['23시', 'Saturday', '가전'],
 ['23시', 'Saturday', '속옷'],
 ['23시', 'Saturday', '의류'],
 ['23시', 'Sunday', '가전'],
 ['23시', 'Sunday', '속옷'],
 ['23시', 'Sunday', '의류'],
 ['23시', 'Thursday', '가전'],
 ['23시', 'Tuesday', '가전'],
 ['23시', 'Tuesday', '속옷'],
 ['23시', 'Wednesday', '가구'],
 ['23시', 'Wednesday', '속옷'],
 ['23시', 'Wednesday', '이미용'],
 ['6시', 'Friday', '생활용품'],
 ['6시', 'Friday', '속옷'],
 ['6시', 'Friday', '의류'],
 ['6시', 'Monday', '건강기능'],
 ['6시', 'Monday', '속옷'],
 ['6시', 'Monday', '의류'],
 ['6시', 'Monday', '주방'],
 ['6시', 'Saturday', '속옷'],
 ['6시', 'Saturday', '의류'],
 ['6시', 'Sunday', '생활용품'],
 ['6시', 'Sunday', '속옷'],
 ['6시', 'Sunday', '의류'],
 ['6시', 'Thursday', '생활용품'],
 ['6시', 'Thursday', '의류'],
 ['6시', 'Thursday', '주방'],
 ['6시', 'Tuesday', '속옷'],
 ['6시', 'Tuesday', '의류'],
 ['6시', 'Wednesday', '속옷'],
 ['6시', 'Wednesday', '의류'],
 ['6시', 'Wednesday', '주방'],
 ['7시', 'Friday', '건강기능'],
 ['7시', 'Friday', '생활용품'],
 ['7시', 'Friday', '의류'],
 ['7시', 'Friday', '잡화'],
 ['7시', 'Monday', '속옷'],
 ['7시', 'Monday', '의류'],
 ['7시', 'Monday', '잡화'],
 ['7시', 'Monday', '주방'],
 ['7시', 'Saturday', '속옷'],
 ['7시', 'Saturday', '의류'],
 ['7시', 'Sunday', '건강기능'],
 ['7시', 'Sunday', '속옷'],
 ['7시', 'Sunday', '의류'],
 ['7시', 'Thursday', '건강기능'],
 ['7시', 'Thursday', '의류'],
 ['7시', 'Thursday', '주방'],
 ['7시', 'Tuesday', '건강기능'],
 ['7시', 'Tuesday', '속옷'],
 ['7시', 'Tuesday', '의류'],
 ['7시', 'Tuesday', '이미용'],
 ['7시', 'Tuesday', '잡화'],
 ['7시', 'Wednesday', '건강기능'],
 ['7시', 'Wednesday', '의류'],
 ['7시', 'Wednesday', '잡화'],
 ['8시', 'Friday', '생활용품'],
 ['8시', 'Friday', '의류'],
 ['8시', 'Friday', '잡화'],
 ['8시', 'Monday', '속옷'],
 ['8시', 'Monday', '의류'],
 ['8시', 'Monday', '잡화'],
 ['8시', 'Monday', '주방'],
 ['8시', 'Saturday', '의류'],
 ['8시', 'Saturday', '잡화'],
 ['8시', 'Saturday', '주방'],
 ['8시', 'Sunday', '속옷'],
 ['8시', 'Sunday', '의류'],
 ['8시', 'Thursday', '속옷'],
 ['8시', 'Thursday', '의류'],
 ['8시', 'Thursday', '잡화'],
 ['8시', 'Tuesday', '속옷'],
 ['8시', 'Tuesday', '의류'],
 ['8시', 'Tuesday', '잡화'],
 ['8시', 'Tuesday', '주방'],
 ['8시', 'Wednesday', '속옷'],
 ['8시', 'Wednesday', '의류'],
 ['8시', 'Wednesday', '주방'],
 ['9시', 'Friday', '의류'],
 ['9시', 'Friday', '잡화'],
 ['9시', 'Friday', '주방'],
 ['9시', 'Monday', '의류'],
 ['9시', 'Monday', '잡화'],
 ['9시', 'Monday', '주방'],
 ['9시', 'Saturday', '의류'],
 ['9시', 'Saturday', '잡화'],
 ['9시', 'Saturday', '주방'],
 ['9시', 'Sunday', '의류'],
 ['9시', 'Sunday', '잡화'],
 ['9시', 'Sunday', '주방'],
 ['9시', 'Thursday', '의류'],
 ['9시', 'Thursday', '잡화'],
 ['9시', 'Thursday', '주방'],
 ['9시', 'Tuesday', '속옷'],
 ['9시', 'Tuesday', '의류'],
 ['9시', 'Tuesday', '잡화'],
 ['9시', 'Tuesday', '주방'],
 ['9시', 'Wednesday', '속옷'],
 ['9시', 'Wednesday', '의류'],
 ['9시', 'Wednesday', '잡화'],
 ['9시', 'Wednesday', '주방']]

In [174]:
list(frequent_itemsets.iloc[740][1])

['8시', 'Monday', '주방']

# 시청률로 연관조합 필터링

In [175]:
amount = data.groupby('상품군')['취급액','시청률'].mean().reset_index()
amount

     상품군           취급액       시청률
0     가구  1.265471e+07  0.004072
1     가전  1.879933e+07  0.003629
2   건강기능  2.557712e+07  0.003113
3    농수축  4.272457e+07  0.005759
4   생활용품  1.865005e+07  0.004610
5     속옷  2.613721e+07  0.004070
6     의류  2.442927e+07  0.004453
7    이미용  3.779511e+07  0.004229
8     잡화  1.686131e+07  0.006231
9     주방  1.930615e+07  0.004638
10    침구  1.052947e+07  0.003290

In [176]:
data['상품군평균시청률'] = np.nan

In [177]:
data['상품군'][0]

'의류'

In [178]:
for i in range(len(data)):
    for j in range(len(amount)):
        if data['상품군'][i] == amount['상품군'][j]:
            data['상품군평균시청률'][i] = amount['시청률'][j]

In [179]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35379 entries, 0 to 35378
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   방송일시      35379 non-null  datetime64[ns]
 1   노출(분)     35379 non-null  float64
 2   마더코드      35379 non-null  int64
 3   상품코드      35379 non-null  int64
 4   상품명       35379 non-null  object
 5   상품군       35379 non-null  object
 6   판매단가      35379 non-null  int64
 7   취급액       35379 non-null  float64
 8   세부상품군     35379 non-null  object
 9   브랜드       35379 non-null  object
 10  시청률       35379 non-null  float64
 11  건수        35379 non-null  float64
 12  방송날짜      35379 non-null  object
 13  방송월       35379 non-null  int64
 14  방송일       35379 non-null  int64
 15  방송요일      35379 non-null  object
 16  방송시간      35379 non-null  object
 17  평일/주말     35379 non-null  int64
 18  공휴일       35379 non-null  int64
 19  계절        35379 non-null  object
 20  방송회차      35379 non-null  int64
 21  무이자/일시불   12548 non-null  object
 22  상품군평균시청률  35379 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(8), object(9)
memory usage: 6.2+ MB

In [180]:
tv = data.groupby(['방송시간','방송요일','상품군','상품군평균시청률'])['시청률'].mean().reset_index()
tv

     방송시간       방송요일   상품군  상품군평균시청률       시청률
0      0시     Friday    가구  0.004072  0.002350
1      0시     Friday    가전  0.003629  0.002568
2      0시     Friday  건강기능  0.003113  0.007692
3      0시     Friday   농수축  0.005759  0.000550
4      0시     Friday  생활용품  0.004610  0.002650
...   ...        ...   ...       ...       ...
1190   9시  Wednesday    속옷  0.004070  0.003339
1191   9시  Wednesday    의류  0.004453  0.005764
1192   9시  Wednesday   이미용  0.004229  0.002725
1193   9시  Wednesday    잡화  0.006231  0.002334
1194   9시  Wednesday    주방  0.004638  0.005472

[1195 rows x 5 columns]

In [181]:
# 조합중 상품평균시청률보다 낮은것 제거
new_combin = []
for i in range(len(tv)):
    for j in combin:
        if tv.iloc[i][3] <= tv.iloc[i][4]:
            if tv['방송시간'][i] == j[0] and tv['방송요일'][i] == j[1] and tv['상품군'][i] == j[2]:
                new_combin.append(j)

In [182]:
new_combin

[['0시', 'Friday', '속옷'],
 ['0시', 'Monday', '생활용품'],
 ['0시', 'Saturday', '의류'],
 ['0시', 'Thursday', '의류'],
 ['0시', 'Thursday', '잡화'],
 ['0시', 'Tuesday', '속옷'],
 ['10시', 'Friday', '의류'],
 ['10시', 'Friday', '주방'],
 ['10시', 'Monday', '농수축'],
 ['10시', 'Monday', '의류'],
 ['10시', 'Saturday', '의류'],
 ['10시', 'Saturday', '잡화'],
 ['10시', 'Sunday', '의류'],
 ['10시', 'Thursday', '농수축'],
 ['10시', 'Tuesday', '의류'],
 ['10시', 'Tuesday', '잡화'],
 ['10시', 'Wednesday', '속옷'],
 ['10시', 'Wednesday', '주방'],
 ['11시', 'Monday', '농수축'],
 ['11시', 'Monday', '주방'],
 ['11시', 'Saturday', '의류'],
 ['11시', 'Sunday', '농수축'],
 ['11시', 'Sunday', '잡화'],
 ['11시', 'Thursday', '농수축'],
 ['11시', 'Thursday', '의류'],
 ['11시', 'Thursday', '잡화'],
 ['11시', 'Tuesday', '농수축'],
 ['11시', 'Wednesday', '농수축'],
 ['11시', 'Wednesday', '의류'],
 ['12시', 'Friday', '잡화'],
 ['12시', 'Monday', '농수축'],
 ['12시', 'Thursday', '주방'],
 ['12시', 'Tuesday', '농수축'],
 ['12시', 'Tuesday', '주방'],
 ['13시', 'Friday', '주방'],
 ['13시', 'Monday', '농수축'],
 ['13시', 'Monday', '의류'],
 ['13시', 'Monday', '주방'],
 ['13시', 'Sunday', '잡화'],
 ['13시', 'Thursday', '잡화'],
 ['13시', 'Tuesday', '속옷'],
 ['13시', 'Tuesday', '주방'],
 ['13시', 'Wednesday', '농수축'],
 ['13시', 'Wednesday', '주방'],
 ['14시', 'Friday', '속옷'],
 ['14시', 'Monday', '농수축'],
 ['14시', 'Monday', '속옷'],
 ['14시', 'Monday', '주방'],
 ['14시', 'Saturday', '속옷'],
 ['14시', 'Saturday', '의류'],
 ['14시', 'Saturday', '주방'],
 ['14시', 'Sunday', '속옷'],
 ['14시', 'Sunday', '의류'],
 ['14시', 'Sunday', '주방'],
 ['14시', 'Thursday', '의류'],
 ['14시', 'Thursday', '주방'],
 ['14시', 'Tuesday', '주방'],
 ['14시', 'Wednesday', '속옷'],
 ['15시', 'Friday', '주방'],
 ['15시', 'Monday', '속옷'],
 ['15시', 'Monday', '주방'],
 ['15시', 'Saturday', '속옷'],
 ['15시', 'Saturday', '의류'],
 ['15시', 'Saturday', '주방'],
 ['15시', 'Sunday', '농수축'],
 ['15시', 'Sunday', '의류'],
 ['15시', 'Tuesday', '속옷'],
 ['15시', 'Tuesday', '주방'],
 ['15시', 'Wednesday', '주방'],
 ['16시', 'Monday', '농수축'],
 ['16시', 'Saturday', '주방'],
 ['16시', 'Sunday', '농수축'],
 ['16시', 'Sunday', '이미용'],
 ['16시', 'Sunday', '주방'],
 ['16시', 'Thursday', '농수축'],
 ['16시', 'Tuesday', '농수축'],
 ['17시', 'Friday', '농수축'],
 ['17시', 'Monday', '농수축'],
 ['17시', 'Monday', '주방'],
 ['17시', 'Saturday', '농수축'],
 ['17시', 'Sunday', '농수축'],
 ['17시', 'Sunday', '주방'],
 ['17시', 'Tuesday', '주방'],
 ['17시', 'Wednesday', '주방'],
 ['18시', 'Friday', '주방'],
 ['18시', 'Monday', '주방'],
 ['18시', 'Thursday', '농수축'],
 ['19시', 'Monday', '속옷'],
 ['19시', 'Monday', '의류'],
 ['19시', 'Monday', '이미용'],
 ['19시', 'Tuesday', '주방'],
 ['19시', 'Wednesday', '속옷'],
 ['1시', 'Friday', '속옷'],
 ['1시', 'Monday', '의류'],
 ['1시', 'Saturday', '속옷'],
 ['1시', 'Saturday', '잡화'],
 ['1시', 'Thursday', '속옷'],
 ['1시', 'Tuesday', '생활용품'],
 ['1시', 'Tuesday', '의류'],
 ['1시', 'Tuesday', '잡화'],
 ['1시', 'Wednesday', '잡화'],
 ['20시', 'Friday', '주방'],
 ['20시', 'Thursday', '의류'],
 ['20시', 'Tuesday', '가전'],
 ['20시', 'Tuesday', '농수축'],
 ['20시', 'Tuesday', '의류'],
 ['20시', 'Wednesday', '속옷'],
 ['20시', 'Wednesday', '의류'],
 ['21시', 'Sunday', '가전'],
 ['21시', 'Thursday', '가구'],
 ['21시', 'Thursday', '가전'],
 ['21시', 'Tuesday', '가구'],
 ['21시', 'Tuesday', '가전'],
 ['21시', 'Wednesday', '가전'],
 ['22시', 'Saturday', '가구'],
 ['22시', 'Sunday', '가전'],
 ['22시', 'Thursday', '가전'],
 ['22시', 'Tuesday', '가전'],
 ['23시', 'Monday', '생활용품'],
 ['23시', 'Monday', '의류'],
 ['23시', 'Sunday', '가전'],
 ['23시', 'Sunday', '의류'],
 ['23시', 'Tuesday', '가전'],
 ['23시', 'Wednesday', '속옷'],
 ['6시', 'Friday', '생활용품'],
 ['6시', 'Sunday', '속옷'],
 ['7시', 'Friday', '건강기능'],
 ['7시', 'Monday', '속옷'],
 ['7시', 'Saturday', '속옷'],
 ['7시', 'Thursday', '건강기능'],
 ['8시', 'Friday', '생활용품'],
 ['8시', 'Monday', '속옷'],
 ['8시', 'Sunday', '속옷'],
 ['8시', 'Tuesday', '속옷'],
 ['8시', 'Tuesday', '잡화'],
 ['8시', 'Wednesday', '의류'],
 ['9시', 'Friday', '잡화'],
 ['9시', 'Friday', '주방'],
 ['9시', 'Monday', '의류'],
 ['9시', 'Saturday', '잡화'],
 ['9시', 'Sunday', '주방'],
 ['9시', 'Thursday', '의류'],
 ['9시', 'Tuesday', '의류'],
 ['9시', 'Wednesday', '의류'],
 ['9시', 'Wednesday', '주방']]

In [183]:
len(new_combin)

145

In [184]:
newcombindata = pd.DataFrame(new_combin, columns=['방송시간','방송요일','상품군'])

In [185]:
newcombindata['상품군'].value_counts()

주방      32
의류      29
속옷      25
농수축     23
잡화      14
가전      10
생활용품     5
가구       3
건강기능     2
이미용      2
Name: 상품군, dtype: int64

# Train 데이터에 적용

In [188]:
data['프라임시간'] = np.nan

In [189]:
# 최적의 조합(프라임시간)이라면 1을 삽입
for i in range(len(data)):
    for j in new_combin:
        if data['방송시간'][i] == j[0] and data['방송요일'][i] == j[1] and data['상품군'][i] == j[2]:
            data['프라임시간'][i] = 1

In [190]:
# 최적의 조합(프라임시간)이 아니라면 0을 삽입
data['프라임시간'] = data['프라임시간'].fillna(0)

In [191]:
data['프라임시간'].value_counts()

0.0    26057
1.0     9322
Name: 프라임시간, dtype: int64

In [192]:
data

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,세부상품군,브랜드,...,방송일,방송요일,방송시간,평일/주말,공휴일,계절,방송회차,무이자/일시불,상품군평균시청률,프라임시간
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,니트/터틀넥/기모,테이트,...,1,Tuesday,6시,0,1,겨울,1,NaN,0.004453,0.0
1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,니트/터틀넥/기모,테이트,...,1,Tuesday,6시,0,1,겨울,1,NaN,0.004453,0.0
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,니트/터틀넥/기모,테이트,...,1,Tuesday,6시,0,1,겨울,2,NaN,0.004453,0.0
3,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,니트/터틀넥/기모,테이트,...,1,Tuesday,6시,0,1,겨울,2,NaN,0.004453,0.0
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0,니트/터틀넥/기모,테이트,...,1,Tuesday,6시,0,1,겨울,3,NaN,0.004453,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0,밥솥,쿠첸,...,31,Tuesday,23시,0,0,겨울,2,일시불,0.004638,0.0
35375,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000.0,밥솥,쿠첸,...,1,Wednesday,0시,0,1,겨울,3,무이자,0.004638,0.0
35376,2020-01-01 00:00:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000.0,밥솥,쿠첸,...,1,Wednesday,0시,0,1,겨울,3,일시불,0.004638,0.0
35377,2020-01-01 00:00:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000.0,밥솥,쿠첸,...,1,Wednesday,0시,0,1,겨울,3,무이자,0.004638,0.0
35378,2020-01-01 00:00:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000.0,밥솥,쿠첸,...,1,Wednesday,0시,0,1,겨울,3,일시불,0.004638,0.0

In [193]:
datas['프라임시간'] = data['프라임시간']

In [194]:
datas.to_csv('data/train_data_05.csv', encoding='utf-8-sig')

## 데이터 체크

In [77]:
prime = data[data['프라임시간']==1]

In [78]:
kk = prime.groupby(['방송시간','방송요일','상품군'])['취급액'].count().reset_index()

In [79]:
kk

    방송시간       방송요일   상품군  취급액
0     0시     Friday    속옷   43
1     0시     Monday  생활용품   51
2     0시   Saturday    의류   45
3     0시   Thursday    의류   64
4     0시   Thursday    잡화   60
..   ...        ...   ...  ...
140   9시     Sunday    주방   40
141   9시   Thursday    의류   47
142   9시    Tuesday    의류   30
143   9시  Wednesday    의류   64
144   9시  Wednesday    주방   59

[145 rows x 4 columns]

In [80]:
kk[kk['상품군']=='건강기능']

    방송시간      방송요일   상품군  취급액
126   7시    Friday  건강기능   38
129   7시  Thursday  건강기능   31

In [81]:
kk[kk['상품군']=='생활용품']

    방송시간     방송요일   상품군  취급액
1     0시   Monday  생활용품   51
97    1시  Tuesday  생활용품   34
118  23시   Monday  생활용품   66
124   6시   Friday  생활용품   37
130   8시   Friday  생활용품   63

In [82]:
kk[kk['상품군']=='가전']

    방송시간       방송요일 상품군  취급액
103  20시    Tuesday  가전   61
108  21시     Sunday  가전  226
110  21시   Thursday  가전  240
112  21시    Tuesday  가전  243
113  21시  Wednesday  가전  229
115  22시     Sunday  가전  268
116  22시   Thursday  가전  267
117  22시    Tuesday  가전  155
120  23시     Sunday  가전  100
122  23시    Tuesday  가전   74

In [83]:
kk[kk['상품군']=='농수축']

    방송시간       방송요일  상품군  취급액
8    10시     Monday  농수축   28
13   10시   Thursday  농수축   37
18   11시     Monday  농수축   39
21   11시     Sunday  농수축   21
23   11시   Thursday  농수축   46
26   11시    Tuesday  농수축   46
27   11시  Wednesday  농수축   34
30   12시     Monday  농수축   21
32   12시    Tuesday  농수축   24
35   13시     Monday  농수축   24
42   13시  Wednesday  농수축   22
45   14시     Monday  농수축   33
64   15시     Sunday  농수축   30
69   16시     Monday  농수축  139
71   16시     Sunday  농수축   82
74   16시   Thursday  농수축  112
75   16시    Tuesday  농수축  120
76   17시     Friday  농수축  102
77   17시     Monday  농수축  126
79   17시   Saturday  농수축  136
80   17시     Sunday  농수축  104
86   18시   Thursday  농수축  110
104  20시    Tuesday  농수축   23

# Test DATA(6월) 적용

In [120]:
datas = pd.read_csv('data/test_data_04.csv')

In [121]:
data = datas.copy()

In [122]:
data

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,세부상품군,브랜드,방송날짜,방송월,방송일,방송요일,방송시간,평일/주말,공휴일,계절,방송회차,무이자/일시불
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,2020-06-01,6,1,0,06:20:00,0,0,여름,1,NaN
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,2020-06-01,6,1,0,06:40:00,0,0,여름,2,NaN
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,2020-06-01,6,1,0,07:00:00,0,0,여름,3,NaN
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,란쥬,쿠미투니카,2020-06-01,6,1,0,07:20:00,0,0,여름,1,NaN
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,란쥬,쿠미투니카,2020-06-01,6,1,0,07:40:00,0,0,여름,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,2020-07-01,7,1,2,00:20:00,0,0,여름,1,NaN
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,2020-07-01,7,1,2,00:40:00,0,0,여름,2,NaN
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,2020-07-01,7,1,2,01:00:00,0,0,여름,3,NaN
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,티셔츠,아놀드파마,2020-07-01,7,1,2,01:20:00,0,0,여름,1,NaN
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,티셔츠,아놀드파마,2020-07-01,7,1,2,01:40:00,0,0,여름,2,NaN

In [123]:
# 전처리
data['방송일시'] = pd.to_datetime(data['방송일시'])
data['방송시간'] = data['방송일시'].dt.hour
data['방송요일'] = data['방송일시'].dt.day_name()
data["방송시간"] = data["방송시간"].map(str) + "시"

In [124]:
data.groupby('방송시간')

In [125]:
# 필터링된 조합
new_combin

[['0시', 'Friday', '속옷'],
 ['0시', 'Monday', '생활용품'],
 ['0시', 'Saturday', '의류'],
 ['0시', 'Thursday', '의류'],
 ['0시', 'Thursday', '잡화'],
 ['0시', 'Tuesday', '속옷'],
 ['10시', 'Friday', '의류'],
 ['10시', 'Friday', '주방'],
 ['10시', 'Monday', '농수축'],
 ['10시', 'Monday', '의류'],
 ['10시', 'Saturday', '의류'],
 ['10시', 'Saturday', '잡화'],
 ['10시', 'Sunday', '의류'],
 ['10시', 'Thursday', '농수축'],
 ['10시', 'Tuesday', '의류'],
 ['10시', 'Tuesday', '잡화'],
 ['10시', 'Wednesday', '속옷'],
 ['10시', 'Wednesday', '주방'],
 ['11시', 'Monday', '농수축'],
 ['11시', 'Monday', '주방'],
 ['11시', 'Saturday', '의류'],
 ['11시', 'Sunday', '농수축'],
 ['11시', 'Sunday', '잡화'],
 ['11시', 'Thursday', '농수축'],
 ['11시', 'Thursday', '의류'],
 ['11시', 'Thursday', '잡화'],
 ['11시', 'Tuesday', '농수축'],
 ['11시', 'Wednesday', '농수축'],
 ['11시', 'Wednesday', '의류'],
 ['12시', 'Friday', '잡화'],
 ['12시', 'Monday', '농수축'],
 ['12시', 'Thursday', '주방'],
 ['12시', 'Tuesday', '농수축'],
 ['12시', 'Tuesday', '주방'],
 ['13시', 'Friday', '주방'],
 ['13시', 'Monday', '농수축'],
 ['13시', 'Monday', '의류'],
 ['13시', 'Monday', '주방'],
 ['13시', 'Sunday', '잡화'],
 ['13시', 'Thursday', '잡화'],
 ['13시', 'Tuesday', '속옷'],
 ['13시', 'Tuesday', '주방'],
 ['13시', 'Wednesday', '농수축'],
 ['13시', 'Wednesday', '주방'],
 ['14시', 'Friday', '속옷'],
 ['14시', 'Monday', '농수축'],
 ['14시', 'Monday', '속옷'],
 ['14시', 'Monday', '주방'],
 ['14시', 'Saturday', '속옷'],
 ['14시', 'Saturday', '의류'],
 ['14시', 'Saturday', '주방'],
 ['14시', 'Sunday', '속옷'],
 ['14시', 'Sunday', '의류'],
 ['14시', 'Sunday', '주방'],
 ['14시', 'Thursday', '의류'],
 ['14시', 'Thursday', '주방'],
 ['14시', 'Tuesday', '주방'],
 ['14시', 'Wednesday', '속옷'],
 ['15시', 'Friday', '주방'],
 ['15시', 'Monday', '속옷'],
 ['15시', 'Monday', '주방'],
 ['15시', 'Saturday', '속옷'],
 ['15시', 'Saturday', '의류'],
 ['15시', 'Saturday', '주방'],
 ['15시', 'Sunday', '농수축'],
 ['15시', 'Sunday', '의류'],
 ['15시', 'Tuesday', '속옷'],
 ['15시', 'Tuesday', '주방'],
 ['15시', 'Wednesday', '주방'],
 ['16시', 'Monday', '농수축'],
 ['16시', 'Saturday', '주방'],
 ['16시', 'Sunday', '농수축'],
 ['16시', 'Sunday', '이미용'],
 ['16시', 'Sunday', '주방'],
 ['16시', 'Thursday', '농수축'],
 ['16시', 'Tuesday', '농수축'],
 ['17시', 'Friday', '농수축'],
 ['17시', 'Monday', '농수축'],
 ['17시', 'Monday', '주방'],
 ['17시', 'Saturday', '농수축'],
 ['17시', 'Sunday', '농수축'],
 ['17시', 'Sunday', '주방'],
 ['17시', 'Tuesday', '주방'],
 ['17시', 'Wednesday', '주방'],
 ['18시', 'Friday', '주방'],
 ['18시', 'Monday', '주방'],
 ['18시', 'Thursday', '농수축'],
 ['19시', 'Monday', '속옷'],
 ['19시', 'Monday', '의류'],
 ['19시', 'Monday', '이미용'],
 ['19시', 'Tuesday', '주방'],
 ['19시', 'Wednesday', '속옷'],
 ['1시', 'Friday', '속옷'],
 ['1시', 'Monday', '의류'],
 ['1시', 'Saturday', '속옷'],
 ['1시', 'Saturday', '잡화'],
 ['1시', 'Thursday', '속옷'],
 ['1시', 'Tuesday', '생활용품'],
 ['1시', 'Tuesday', '의류'],
 ['1시', 'Tuesday', '잡화'],
 ['1시', 'Wednesday', '잡화'],
 ['20시', 'Friday', '주방'],
 ['20시', 'Thursday', '의류'],
 ['20시', 'Tuesday', '가전'],
 ['20시', 'Tuesday', '농수축'],
 ['20시', 'Tuesday', '의류'],
 ['20시', 'Wednesday', '속옷'],
 ['20시', 'Wednesday', '의류'],
 ['21시', 'Sunday', '가전'],
 ['21시', 'Thursday', '가구'],
 ['21시', 'Thursday', '가전'],
 ['21시', 'Tuesday', '가구'],
 ['21시', 'Tuesday', '가전'],
 ['21시', 'Wednesday', '가전'],
 ['22시', 'Saturday', '가구'],
 ['22시', 'Sunday', '가전'],
 ['22시', 'Thursday', '가전'],
 ['22시', 'Tuesday', '가전'],
 ['23시', 'Monday', '생활용품'],
 ['23시', 'Monday', '의류'],
 ['23시', 'Sunday', '가전'],
 ['23시', 'Sunday', '의류'],
 ['23시', 'Tuesday', '가전'],
 ['23시', 'Wednesday', '속옷'],
 ['6시', 'Friday', '생활용품'],
 ['6시', 'Sunday', '속옷'],
 ['7시', 'Friday', '건강기능'],
 ['7시', 'Monday', '속옷'],
 ['7시', 'Saturday', '속옷'],
 ['7시', 'Thursday', '건강기능'],
 ['8시', 'Friday', '생활용품'],
 ['8시', 'Monday', '속옷'],
 ['8시', 'Sunday', '속옷'],
 ['8시', 'Tuesday', '속옷'],
 ['8시', 'Tuesday', '잡화'],
 ['8시', 'Wednesday', '의류'],
 ['9시', 'Friday', '잡화'],
 ['9시', 'Friday', '주방'],
 ['9시', 'Monday', '의류'],
 ['9시', 'Saturday', '잡화'],
 ['9시', 'Sunday', '주방'],
 ['9시', 'Thursday', '의류'],
 ['9시', 'Tuesday', '의류'],
 ['9시', 'Wednesday', '의류'],
 ['9시', 'Wednesday', '주방']]

In [126]:
data['프라임시간'] = np.nan

In [127]:
# 최적의 조합(프라임시간)이라면 1을 삽입
for i in range(len(data)):
    for j in new_combin:
        if data['방송시간'][i] == j[0] and data['방송요일'][i] == j[1] and data['상품군'][i] == j[2]:
            data['프라임시간'][i] = 1

In [128]:
data

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,세부상품군,브랜드,...,방송월,방송일,방송요일,방송시간,평일/주말,공휴일,계절,방송회차,무이자/일시불,프라임시간
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,...,6,1,Monday,6시,0,0,여름,1,NaN,NaN
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,...,6,1,Monday,6시,0,0,여름,2,NaN,NaN
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,...,6,1,Monday,7시,0,0,여름,3,NaN,NaN
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,란쥬,쿠미투니카,...,6,1,Monday,7시,0,0,여름,1,NaN,1.0
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,란쥬,쿠미투니카,...,6,1,Monday,7시,0,0,여름,2,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,...,7,1,Wednesday,0시,0,0,여름,1,NaN,NaN
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,...,7,1,Wednesday,0시,0,0,여름,2,NaN,NaN
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,...,7,1,Wednesday,1시,0,0,여름,3,NaN,NaN
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,티셔츠,아놀드파마,...,7,1,Wednesday,1시,0,0,여름,1,NaN,NaN
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,티셔츠,아놀드파마,...,7,1,Wednesday,1시,0,0,여름,2,NaN,NaN

In [130]:
data['프라임시간'] = data['프라임시간'].fillna(0)

In [131]:
data['프라임시간'].value_counts()

0.0    2374
1.0     517
Name: 프라임시간, dtype: int64

In [132]:
data

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,세부상품군,브랜드,...,방송월,방송일,방송요일,방송시간,평일/주말,공휴일,계절,방송회차,무이자/일시불,프라임시간
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,...,6,1,Monday,6시,0,0,여름,1,NaN,0.0
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,...,6,1,Monday,6시,0,0,여름,2,NaN,0.0
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,셔츠,잭필드,...,6,1,Monday,7시,0,0,여름,3,NaN,0.0
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,란쥬,쿠미투니카,...,6,1,Monday,7시,0,0,여름,1,NaN,1.0
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,란쥬,쿠미투니카,...,6,1,Monday,7시,0,0,여름,2,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,...,7,1,Wednesday,0시,0,0,여름,1,NaN,0.0
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,...,7,1,Wednesday,0시,0,0,여름,2,NaN,0.0
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,NaN,NaN,...,7,1,Wednesday,1시,0,0,여름,3,NaN,0.0
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,티셔츠,아놀드파마,...,7,1,Wednesday,1시,0,0,여름,1,NaN,0.0
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,티셔츠,아놀드파마,...,7,1,Wednesday,1시,0,0,여름,2,NaN,0.0

In [133]:
datas['프라임시간'] = data['프라임시간']

In [134]:
datas.to_csv('data/test_data_05.csv', encoding='utf-8-sig')

In [136]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2891 entries, 0 to 2890
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   방송일시     2891 non-null   object
 1   노출(분)    2891 non-null   float64
 2   마더코드     2891 non-null   int64
 3   상품코드     2891 non-null   int64
 4   상품명      2891 non-null   object
 5   상품군      2891 non-null   object
 6   판매단가     2891 non-null   int64
 7   취급액      0 non-null      float64
 8   세부상품군    2716 non-null   object
 9   브랜드      2646 non-null   object
 10  방송날짜     2891 non-null   object
 11  방송월      2891 non-null   int64
 12  방송일      2891 non-null   int64
 13  방송요일     2891 non-null   int64
 14  방송시간     2891 non-null   object
 15  평일/주말    2891 non-null   int64
 16  공휴일      2891 non-null   int64
 17  계절       2891 non-null   object
 18  방송회차     2891 non-null   int64
 19  무이자/일시불  463 non-null    object
 20  프라임시간    2891 non-null   float64
dtypes: float64(3), int64(9), object(9)
memory usage: 474.4+ KB