# 편성표 크롤링

In [2]:
url = 'https://www.uplus.co.kr/css/chgi/chgi/RetrieveTvContentsMFamily.hpi'

In [3]:
headers = {
    'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'    
}

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib import parse
from datetime import datetime
from selenium.webdriver import Chrome
from selenium.webdriver import ChromeOptions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re
import time

In [56]:
#날짜 차이
from datetime import date

d0 = date(2020, 8 ,17)
d1 = date(2019, 12, 31)
delta = d0 - d1
delta.days

230

In [226]:
options = ChromeOptions()
options.add_argument('headless')

driver = Chrome()
driver.get(url)
result = []

In [227]:
# 홈쇼핑 -> ns shop+ 로 이동
driver.find_element_by_xpath('//*[@id="8"]').click()   
driver.find_element_by_xpath('//*[@id="117"]').click()

In [228]:
import time, datetime
page = 0
# 2020-01-01 까지 날짜, 시간, 상품명 크롤링
while page != 230:
    soup = BeautifulSoup(driver.page_source)
    day = soup.select_one('span.date').text.strip()[:-5]
    day = '-'.join(re.findall("\d+", day))
    print(day)
    item_list = soup.select('div.tblType.list table tbody tr')
    error_cnt = 0
    
    for item in item_list:
        hour = item.select_one('td.txtC').text.strip()
        program = item.select_one('td.txtL').text.split('\n')[0]
        result.append([day,hour,program])
    driver.find_element_by_class_name('prev').click()
    page += 1
    time.sleep(2)

2020-08-17
2020-08-16
2020-08-15
2020-08-14
2020-08-13
2020-08-12
2020-08-11
2020-08-10
2020-08-09
2020-08-08
2020-08-07
2020-08-06
2020-08-05
2020-08-04
2020-08-03
2020-08-02
2020-08-01
2020-07-31
2020-07-30
2020-07-29
2020-07-28
2020-07-27
2020-07-26
2020-07-25
2020-07-24
2020-07-23
2020-07-22
2020-07-21
2020-07-20
2020-07-19
2020-07-18
2020-07-17
2020-07-16
2020-07-15
2020-07-14
2020-07-13
2020-07-12
2020-07-11
2020-07-10
2020-07-09
2020-07-08
2020-07-07
2020-07-06
2020-07-05
2020-07-04
2020-07-03
2020-07-02
2020-07-01
2020-06-30
2020-06-29
2020-06-28
2020-06-27
2020-06-26
2020-06-25
2020-06-24
2020-06-23
2020-06-22
2020-06-21
2020-06-20
2020-06-19
2020-06-18
2020-06-17
2020-06-16
2020-06-15
2020-06-14
2020-06-13
2020-06-12
2020-06-11
2020-06-10
2020-06-09
2020-06-08
2020-06-07
2020-06-06
2020-06-05
2020-06-04
2020-06-03
2020-06-02
2020-06-01
2020-05-31
2020-05-30
2020-05-29
2020-05-28
2020-05-27
2020-05-26
2020-05-25
2020-05-24
2020-05-23
2020-05-22
2020-05-21
2020-05-20
2020-05-19
2020-05-18
2020-05-17
2020-05-16
2020-05-15
2020-05-14
2020-05-13
2020-05-12
2020-05-11
2020-05-10
2020-05-09
2020-05-08
2020-05-07
2020-05-06
2020-05-05
2020-05-04
2020-05-03
2020-05-02
2020-05-01
2020-04-30
2020-04-29
2020-04-28
2020-04-27
2020-04-26
2020-04-25
2020-04-24
2020-04-23
2020-04-22
2020-04-21
2020-04-20
2020-04-19
2020-04-18
2020-04-17
2020-04-16
2020-04-15
2020-04-14
2020-04-13
2020-04-12
2020-04-11
2020-04-10
2020-04-09
2020-04-08
2020-04-07
2020-04-06
2020-04-05
2020-04-04
2020-04-03
2020-04-02
2020-04-01
2020-03-31
2020-03-30
2020-03-29
2020-03-28
2020-03-27
2020-03-26
2020-03-25
2020-03-24
2020-03-23
2020-03-22
2020-03-21
2020-03-20
2020-03-19
2020-03-18
2020-03-17
2020-03-16
2020-03-15
2020-03-14
2020-03-13
2020-03-12
2020-03-11
2020-03-10
2020-03-09
2020-03-08
2020-03-07
2020-03-06
2020-03-05
2020-03-04
2020-03-03
2020-03-02
2020-03-01
2020-02-29
2020-02-28
2020-02-27
2020-02-26
2020-02-25
2020-02-24
2020-02-23
2020-02-22
2020-02-21
2020-02-20
2020-02-19
2020-02-18
2020-02-17
2020-02-16
2020-02-15
2020-02-14
2020-02-13
2020-02-12
2020-02-11
2020-02-10
2020-02-09
2020-02-08
2020-02-07
2020-02-06
2020-02-05
2020-02-04
2020-02-03
2020-02-02
2020-02-01
2020-01-31
2020-01-30
2020-01-29
2020-01-28
2020-01-27
2020-01-26
2020-01-25
2020-01-24
2020-01-23
2020-01-22
2020-01-21
2020-01-20
2020-01-19
2020-01-18
2020-01-17
2020-01-16
2020-01-15
2020-01-14
2020-01-13
2020-01-12
2020-01-11
2020-01-10
2020-01-09
2020-01-08
2020-01-07
2020-01-06
2020-01-05
2020-01-04
2020-01-03
2020-01-02
2020-01-01

In [237]:
df = pd.DataFrame(result, 
                  columns=['날짜','시간', '상품명'])
df

              날짜     시간             상품명
0     2020-08-17  00:20        엑사이더워킹머신
1     2020-08-17  01:20              참존
2     2020-08-17  02:00            손질문어
3     2020-08-17  03:00        전철우 고향랭면
4     2020-08-17  03:40        라비오뜨마스크팩
...          ...    ...             ...
5854  2020-01-01  19:20           푸마드로즈
5855  2020-01-01  20:20           현대정수기
5856  2020-01-01  21:20            LGTV
5857  2020-01-01  22:20           장수흙침대
5858  2020-01-01  23:20  비버리힐스폴로 남성기초세트

[5859 rows x 3 columns]

In [238]:
# 날짜, 시간으로 오름차순 정렬
df_rev = df.sort_values(by=['날짜','시간'], axis=0).reset_index()
df_rev

      index          날짜     시간      상품명
0      5834  2020-01-01  00:20     삼성화재
1      5835  2020-01-01  01:20    예다함상조
2      5836  2020-01-01  02:00    예다함상조
3      5837  2020-01-01  02:20  이경제황금관절
4      5838  2020-01-01  03:20   엔웰스마스크
...     ...         ...    ...      ...
5854     21  2020-08-17  19:20   헤드남자속옷
5855     22  2020-08-17  20:20      예초기
5856     23  2020-08-17  21:20    LG냉장고
5857     24  2020-08-17  22:20     LGTV
5858     25  2020-08-17  23:20    예다함상조

[5859 rows x 4 columns]

In [241]:
df_rev = df_rev.drop('index', axis=1)

In [242]:
df_rev

              날짜     시간      상품명
0     2020-01-01  00:20     삼성화재
1     2020-01-01  01:20    예다함상조
2     2020-01-01  02:00    예다함상조
3     2020-01-01  02:20  이경제황금관절
4     2020-01-01  03:20   엔웰스마스크
...          ...    ...      ...
5854  2020-08-17  19:20   헤드남자속옷
5855  2020-08-17  20:20      예초기
5856  2020-08-17  21:20    LG냉장고
5857  2020-08-17  22:20     LGTV
5858  2020-08-17  23:20    예다함상조

[5859 rows x 3 columns]

In [243]:
import pandas as pd
df_rev.to_csv('df_rev.csv', encoding='utf-8-sig', index=False)

In [6]:
import pandas as pd

data = pd.read_csv('df_rev.csv',encoding='utf-8-sig')
data

              날짜     시간      상품명
0     2020-01-01  00:20     삼성화재
1     2020-01-01  01:20    예다함상조
2     2020-01-01  02:00    예다함상조
3     2020-01-01  02:20  이경제황금관절
4     2020-01-01  03:20   엔웰스마스크
...          ...    ...      ...
5854  2020-08-17  19:20   헤드남자속옷
5855  2020-08-17  20:20      예초기
5856  2020-08-17  21:20    LG냉장고
5857  2020-08-17  22:20     LGTV
5858  2020-08-17  23:20    예다함상조

[5859 rows x 3 columns]

In [7]:
data["방송일시"] = data["날짜"].map(str) + ' ' + data["시간"]
# data = data.set_index('방송일시')
data

              날짜     시간      상품명              방송일시
0     2020-01-01  00:20     삼성화재  2020-01-01 00:20
1     2020-01-01  01:20    예다함상조  2020-01-01 01:20
2     2020-01-01  02:00    예다함상조  2020-01-01 02:00
3     2020-01-01  02:20  이경제황금관절  2020-01-01 02:20
4     2020-01-01  03:20   엔웰스마스크  2020-01-01 03:20
...          ...    ...      ...               ...
5854  2020-08-17  19:20   헤드남자속옷  2020-08-17 19:20
5855  2020-08-17  20:20      예초기  2020-08-17 20:20
5856  2020-08-17  21:20    LG냉장고  2020-08-17 21:20
5857  2020-08-17  22:20     LGTV  2020-08-17 22:20
5858  2020-08-17  23:20    예다함상조  2020-08-17 23:20

[5859 rows x 4 columns]

In [8]:
data.방송일시 = pd.to_datetime(data.방송일시)
data

              날짜     시간      상품명                방송일시
0     2020-01-01  00:20     삼성화재 2020-01-01 00:20:00
1     2020-01-01  01:20    예다함상조 2020-01-01 01:20:00
2     2020-01-01  02:00    예다함상조 2020-01-01 02:00:00
3     2020-01-01  02:20  이경제황금관절 2020-01-01 02:20:00
4     2020-01-01  03:20   엔웰스마스크 2020-01-01 03:20:00
...          ...    ...      ...                 ...
5854  2020-08-17  19:20   헤드남자속옷 2020-08-17 19:20:00
5855  2020-08-17  20:20      예초기 2020-08-17 20:20:00
5856  2020-08-17  21:20    LG냉장고 2020-08-17 21:20:00
5857  2020-08-17  22:20     LGTV 2020-08-17 22:20:00
5858  2020-08-17  23:20    예다함상조 2020-08-17 23:20:00

[5859 rows x 4 columns]

In [9]:
data_time = data.copy()

In [10]:
#시간차이 계산을 위하여 방송시간을 한 칸 올린 열 만들기.
#한칸씩 올리면 마지막에 한칸 비는데 이건 대충 채웁니다...어처피 8월데이터는 쓰지 않을것이기 때문에..
data_time['shift'] = data_time.방송일시.shift(-1).fillna('2020-08-17 23:40:00')   
data_time

              날짜     시간      상품명                방송일시                shift
0     2020-01-01  00:20     삼성화재 2020-01-01 00:20:00  2020-01-01 01:20:00
1     2020-01-01  01:20    예다함상조 2020-01-01 01:20:00  2020-01-01 02:00:00
2     2020-01-01  02:00    예다함상조 2020-01-01 02:00:00  2020-01-01 02:20:00
3     2020-01-01  02:20  이경제황금관절 2020-01-01 02:20:00  2020-01-01 03:20:00
4     2020-01-01  03:20   엔웰스마스크 2020-01-01 03:20:00  2020-01-01 04:20:00
...          ...    ...      ...                 ...                  ...
5854  2020-08-17  19:20   헤드남자속옷 2020-08-17 19:20:00  2020-08-17 20:20:00
5855  2020-08-17  20:20      예초기 2020-08-17 20:20:00  2020-08-17 21:20:00
5856  2020-08-17  21:20    LG냉장고 2020-08-17 21:20:00  2020-08-17 22:20:00
5857  2020-08-17  22:20     LGTV 2020-08-17 22:20:00  2020-08-17 23:20:00
5858  2020-08-17  23:20    예다함상조 2020-08-17 23:20:00  2020-08-17 23:40:00

[5859 rows x 5 columns]

In [11]:
import datetime
tv = []
for i in range(len(data_time)):
    try:
        tv.append((data_time.loc[i]['shift'] - data_time.loc[i]['방송일시']).seconds / 60)
    except:
        tv.append(0)

In [12]:
len(tv)

5859

In [13]:
data_time['노출(분)'] = tv
data_time

,날짜,시간,상품명,방송일시,shift,노출(분)
0,2020-01-01,00:20,삼성화재,2020-01-01 00:20:00,2020-01-01 01:20:00,60.0
1,2020-01-01,01:20,예다함상조,2020-01-01 01:20:00,2020-01-01 02:00:00,40.0
2,2020-01-01,02:00,예다함상조,2020-01-01 02:00:00,2020-01-01 02:20:00,20.0
3,2020-01-01,02:20,이경제황금관절,2020-01-01 02:20:00,2020-01-01 03:20:00,60.0
4,2020-01-01,03:20,엔웰스마스크,2020-01-01 03:20:00,2020-01-01 04:20:00,60.0
...,...,...,...,...,...,...
5854,2020-08-17,19:20,헤드남자속옷,2020-08-17 19:20:00,2020-08-17 20:20:00,60.0
5855,2020-08-17,20:20,예초기,2020-08-17 20:20:00,2020-08-17 21:20:00,60.0
5856,2020-08-17,21:20,LG냉장고,2020-08-17 21:20:00,2020-08-17 22:20:00,60.0
5857,2020-08-17,22:20,LGTV,2020-08-17 22:20:00,2020-08-17 23:20:00,60.0
5858,2020-08-17,23:20,예다함상조,2020-08-17 23:20:00,2020-08-17 23:40:00,0.0

In [14]:
data_time = data_time.drop('shift', axis=1)
data_time

              날짜     시간      상품명                방송일시  노출(분)
0     2020-01-01  00:20     삼성화재 2020-01-01 00:20:00   60.0
1     2020-01-01  01:20    예다함상조 2020-01-01 01:20:00   40.0
2     2020-01-01  02:00    예다함상조 2020-01-01 02:00:00   20.0
3     2020-01-01  02:20  이경제황금관절 2020-01-01 02:20:00   60.0
4     2020-01-01  03:20   엔웰스마스크 2020-01-01 03:20:00   60.0
...          ...    ...      ...                 ...    ...
5854  2020-08-17  19:20   헤드남자속옷 2020-08-17 19:20:00   60.0
5855  2020-08-17  20:20      예초기 2020-08-17 20:20:00   60.0
5856  2020-08-17  21:20    LG냉장고 2020-08-17 21:20:00   60.0
5857  2020-08-17  22:20     LGTV 2020-08-17 22:20:00   60.0
5858  2020-08-17  23:20    예다함상조 2020-08-17 23:20:00    0.0

[5859 rows x 5 columns]

In [15]:
data_time['노출(분)'].unique()

array([ 60.,  40.,  20.,  80.,  30., 100.,  10.,   0.])

In [16]:
import pandas as pd
data_time.to_csv('data/ns_crawling.csv', encoding='utf-8-sig', index=False)

# 상품군 붙이기

In [15]:
import pandas as pd
data_time = pd.read_csv('data/ns_crawling.csv', encoding='utf-8-sig')

In [16]:
data_time

              날짜     시간      상품명                 방송일시  노출(분)
0     2020-01-01  00:20     삼성화재  2020-01-01 00:20:00   60.0
1     2020-01-01  01:20    예다함상조  2020-01-01 01:20:00   40.0
2     2020-01-01  02:00    예다함상조  2020-01-01 02:00:00   20.0
3     2020-01-01  02:20  이경제황금관절  2020-01-01 02:20:00   60.0
4     2020-01-01  03:20   엔웰스마스크  2020-01-01 03:20:00   60.0
...          ...    ...      ...                  ...    ...
5854  2020-08-17  19:20   헤드남자속옷  2020-08-17 19:20:00   60.0
5855  2020-08-17  20:20      예초기  2020-08-17 20:20:00   60.0
5856  2020-08-17  21:20    LG냉장고  2020-08-17 21:20:00   60.0
5857  2020-08-17  22:20     LGTV  2020-08-17 22:20:00   60.0
5858  2020-08-17  23:20    예다함상조  2020-08-17 23:20:00    0.0

[5859 rows x 5 columns]

## 메인데이터로 1차로 상품군 붙이기

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('data/train_data_06.csv', encoding = 'utf-8', index_col=0)

In [5]:
data

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,브랜드,중분류,...,방송회차,무이자/일시불,프라임시간,평균기온(°C),강수량(mm),풍속(m/s),습도(%),전운량(10분위),체감온도,비옴
index,,,,,,,,,,,,,,,,,,,,,
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,테이트,남성의류,...,1,NaN,0.0,-8.05,0.0,1.00,73.0,3.5,-9.8,0
1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,테이트,여성의류,...,1,NaN,0.0,-8.05,0.0,1.00,73.0,3.5,-9.8,0
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,테이트,남성의류,...,2,NaN,0.0,-8.05,0.0,1.00,73.0,3.5,-9.8,0
3,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,테이트,여성의류,...,2,NaN,0.0,-8.05,0.0,1.00,73.0,3.5,-9.8,0
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0,테이트,남성의류,...,3,NaN,0.0,-8.05,0.0,1.00,73.0,3.5,-9.8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0,쿠첸,주방가전,...,2,일시불,0.0,-7.40,0.0,0.00,57.0,4.5,8.5,0
35375,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000.0,쿠첸,주방가전,...,3,무이자,0.0,-6.25,0.0,0.75,51.0,9.0,-7.0,0
35376,2020-01-01 00:00:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000.0,쿠첸,주방가전,...,3,일시불,0.0,-6.25,0.0,0.75,51.0,9.0,-7.0,0
35377,2020-01-01 00:00:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000.0,쿠첸,주방가전,...,3,무이자,0.0,-6.25,0.0,0.75,51.0,9.0,-7.0,0
35378,2020-01-01 00:00:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000.0,쿠첸,주방가전,...,3,일시불,0.0,-6.25,0.0,0.75,51.0,9.0,-7.0,0

In [7]:
cloth = data[data['상품군'] == '의류']
kitchen = data[data['상품군'] == '주방']
stuff = data[data['상품군'] == '잡화']
furniture = data[data['상품군'] == '가구']
appliances = data[data['상품군'] == '가전']
food = data[data['상품군'] == '농수축']
underwear = data[data['상품군'] == '속옷']
living = data[data['상품군'] == '생활용품']
hairdressing = data[data['상품군'] == '이미용']
bedding = data[data['상품군'] == '침구']
health = data[data['상품군'] == '건강기능']

In [25]:
cloth_list = list(set(list(cloth['브랜드']) + ['겨울팬츠', '니트','터틀넥','기모', '무스탕', '베스트', '블라우스', '셔츠', '수트', '앙상블', '자켓', '코트', '트레이닝', '티셔츠', '패딩', '팬츠']))
kitchen_list = list(set(list(kitchen['브랜드']) + ['가마솥', '가스레인지', '그릇', '그릴', '냄비', '다지기', '도마', '맷돌', '멀티쿡', '믹서기', '수세미', '식기건조기', '식기건조대', '식기세척기', '식칼', '싱크선반', '압력밥솥', '에어프라이어', '오븐', '용기', '전기밥솥', '전자레인지', '죽제조기', '중탕기', '지퍼백', '진공포장기', '착즙기', '커피머신', '텀블러', '티메이커', '포트', '프라이팬', '행주']))
stuff_list = list(set(list(stuff['브랜드']) + ['런닝화', '모자', '방한화', '백팩', '벨트', '부츠', '샌들', '선글라스', '숄더백', '스니커즈', '스카프','머플러', '슬립온', '신발', '여성백', '여성용가방', '여행가방', '우산','양산', '워킹화', '장갑', '주얼리', '지갑', '크로스백', '토트백', '트레일화', '트레킹화', '펌프스', '핸드백']))
furniture_list = list(set(list(furniture['브랜드']) + ['붙박이장', '서랍장','화장대', '소파', '욕실가구', 
                                                    '침대', '침실가구세트']))
appliances_list = list(set(list(appliances['브랜드']) + ['TV', '건조기', '공기청정기', '기타_가전', 
                                                      '김치냉장고', '냉장고', '노트북', '세탁기', '에어컨', '청소기']))
underwear_list = list(set(list(underwear['브랜드']) + ['내의','웨어', '드로즈', '란쥬', '런닝', '레깅스', '베이스레이어', '브라','팬티', '언더셔츠', '탑', '트렁크']))
living_list = list(set(list(living['브랜드']) + ['교자상', '금고', '기타_생활용품', '도어락', '리빙박스', '마사지기', '마스크', '매트리스', '목견인기기', '벽지', '비데', '샤워기', '선글라스', '예초기', '온수매트', '온열매트', '일반청소기', '카페트매트', '패치']))
hairdressing_list = list(set(list(hairdressing['브랜드']) + ['기초스킨케어세트', '립스틱', '바디', '삼푸,트리트먼트', '선스틱', '세럼', '아이메이크업', '젤네일스트립', '쿠션','팩트', '크림', '클렌징', '헤어에센스']))
bedding_list = list(set(list(bedding['브랜드']) + ['대자리', '암막커튼', '침구세트', '카페트']))
health_list = list(set(list(health['브랜드']) + ['건강기능식품', '건강즙','건강액', '다이어트식품', '두유', '밀싹클렌즈', '분말', '생식', '석류', '유산균', '콜라겐', '해죽순', '홍삼', '환']))
food_list = list(set(list(food['브랜드']) + ['갈비', '곱창', '김치', '꼬막', '꽃게', '낙지', '닭발', '대구', '두유', '모시떡', '문어', '새우', '생선', '쌀', '오징어', '장어', '재첩국', '전복', '쥐포', '탕', '홍어', '황태']))
mu = ['삼성화재','화재','상조','보험','정수기','라이프','여행','방송','리빙','영어','캐피탈','렌탈','아이스크림홈런',
     '(렌탈)','휴대폰','타이어','정보방','숙박권','수도119','싹쓰리','수도','한국금거래소','안마의자','슬리미','음식물처리기','팻밀리아',
     '팔로모매트리스']

In [27]:
underwear_list.extend(['오렐리안','헤드언더셔츠'])

In [28]:
underwear_list

['런닝',
 '에버라스트',
 '실크트리',
 'LSX',
 '코몽트',
 '브라',
 '투홀릭',
 '언더셔츠',
 '베이스레이어',
 '남영비비안',
 '오렐리안',
 '발레리',
 '기타_속옷',
 '헤드',
 '루시헨느',
 '라쉬반',
 '트렁크',
 'BBC&IZUMI',
 '레깅스',
 '헤스떼벨',
 '팬티',
 '오모떼',
 '란쥬',
 '히트융',
 '란체티',
 '몬테밀라노',
 '푸마',
 '크로커다일',
 '드로즈',
 '리복',
 '쿠미투니카',
 '로베르타 디 까메리노',
 '레이프릴',
 '컬럼비아',
 '아키',
 '카파',
 '뷰티플렉스',
 '내의/웨어',
 '탑',
 '저스트마이사이즈',
 '오가닉뷰티',
 '벨레즈온',
 '댄스킨',
 '오렐리안',
 '헤드언더셔츠']

In [29]:
living_list.extend(['보국','샤프란','칫솔','칫솔살균기', '치약'])

In [30]:
stuff_list.extend(['마리끌레르','페리엘리스선글라스'])

In [31]:
food_list.extend(['드립커피'])

In [32]:
product = []
for i in range(len(data_time)):
    if any(x in data_time.iloc[i][2] for x in cloth_list):
        product.append('의류')
    elif any(x in data_time.iloc[i][2] for x in mu):
        product.append('무형')
    elif any(x in data_time.iloc[i][2] for x in kitchen_list):
        product.append('주방')
    elif any(x in data_time.iloc[i][2] for x in stuff_list):
        product.append('잡화')   
    elif any(x in data_time.iloc[i][2] for x in living_list):
        product.append('생활용품')
    elif any(x in data_time.iloc[i][2] for x in furniture_list):
        product.append('가구')        
    elif any(x in data_time.iloc[i][2] for x in appliances_list):
        product.append('가전')
    elif any(x in data_time.iloc[i][2] for x in underwear_list):
        product.append('속옷')
    elif any(x in data_time.iloc[i][2] for x in hairdressing_list):
        product.append('이미용')        
    elif any(x in data_time.iloc[i][2] for x in bedding_list):
        product.append('침구')        
    elif any(x in data_time.iloc[i][2] for x in health_list):
        product.append('건강기능')        
    elif any(x in data_time.iloc[i][2] for x in food_list):
        product.append('농수축')        
    else:
        product.append('미정')

In [18]:
data_time['상품군'] = product
data_time

              날짜     시간      상품명                 방송일시  노출(분)   상품군
0     2020-01-01  00:20     삼성화재  2020-01-01 00:20:00   60.0    무형
1     2020-01-01  01:20    예다함상조  2020-01-01 01:20:00   40.0    무형
2     2020-01-01  02:00    예다함상조  2020-01-01 02:00:00   20.0    무형
3     2020-01-01  02:20  이경제황금관절  2020-01-01 02:20:00   60.0  건강기능
4     2020-01-01  03:20   엔웰스마스크  2020-01-01 03:20:00   60.0    미정
...          ...    ...      ...                  ...    ...   ...
5854  2020-08-17  19:20   헤드남자속옷  2020-08-17 19:20:00   60.0    속옷
5855  2020-08-17  20:20      예초기  2020-08-17 20:20:00   60.0    미정
5856  2020-08-17  21:20    LG냉장고  2020-08-17 21:20:00   60.0    가전
5857  2020-08-17  22:20     LGTV  2020-08-17 22:20:00   60.0    가전
5858  2020-08-17  23:20    예다함상조  2020-08-17 23:20:00    0.0    무형

[5859 rows x 6 columns]

In [19]:
complete = data_time[data_time['상품군'] != '미정']
complete

              날짜     시간       상품명                 방송일시  노출(분)   상품군
0     2020-01-01  00:20      삼성화재  2020-01-01 00:20:00   60.0    무형
1     2020-01-01  01:20     예다함상조  2020-01-01 01:20:00   40.0    무형
2     2020-01-01  02:00     예다함상조  2020-01-01 02:00:00   20.0    무형
3     2020-01-01  02:20   이경제황금관절  2020-01-01 02:20:00   60.0  건강기능
6     2020-01-01  05:20      삼성화재  2020-01-01 05:20:00   60.0    무형
...          ...    ...       ...                  ...    ...   ...
5850  2020-08-17  15:20  LG통돌이세탁기  2020-08-17 15:20:00   60.0    가전
5854  2020-08-17  19:20    헤드남자속옷  2020-08-17 19:20:00   60.0    속옷
5856  2020-08-17  21:20     LG냉장고  2020-08-17 21:20:00   60.0    가전
5857  2020-08-17  22:20      LGTV  2020-08-17 22:20:00   60.0    가전
5858  2020-08-17  23:20     예다함상조  2020-08-17 23:20:00    0.0    무형

[3603 rows x 6 columns]

## 2차로 상품군 붙이기

In [20]:
no = data_time[data_time['상품군'] == '미정']
no['상품명'].unique()

array(['엔웰스마스크', '박경호녹용활력', '도가니탕', '손질갑오징어', '관절팔팔', '아이러브허브', '브루마스',
       '암블로슈즈', '조이앤피스', '석류즙', '통영굴', '고창 고구마', '팔레오', '프로닥스시트세제',
       '제니하우스염색제', '베트남망고', '쥐포', '오메가큐텐', '엔엔에프 패션', '엔웰스마스크1', '액티브코큐텐',
       '제주갈치앤조기', '손질문어', '티포트', '메주', '델키생선구이오븐', '배윤자소곱창전골', '어성초샴푸',
       '궁중손질새우', '손질통오징어', '마르시끄속눈썹드라이기', '뱅네프비누', '반찬명가녹선', '프리지아헤어컬러',
       '닥터슈퍼루테인', '발열장갑', '명품잡화', '황토고구마', '공백세탁조클리너', '녹십자디스크잭허리견인기',
       '샤워기', '텀블러', '연세두유', '밸런스핏', '참소쿠리', '이종임갈비찜', '속눈썹', '마리아꾸르끼',
       '한만두', '비트젯', '에어로팡팡', '보스웰리아', '완도 활전복', '사과배혼합', '제주레드향',
       '섬유유연제', '망개떡', '용대리 황태', '트리트먼트', '한우한판', '바디프랜드', '트래커메이트',
       '들깨탕', '라클라우드매트리스', '나이포발마사지기', '프리모폴딩선반', 'JM마스크', '오즈페토 슬립온',
       '디그노슈즈', '오뚜기만두', '퀸즈모가발', '바세린마스크팩', '엘리닉마스크', '라클라우드 매트리스',
       '벨라수넥크림', '추자도돌미역', '쿠퍼쉐프이지퀵슬라이서', '제주 반건조 옥돔', '광동석류즙', '도라지배즙',
       '바비리스', '턴블러거품기', '콜라겐아임파인', '닥터프리바이오틱스', '오즈페토 슈즈', '동전패치',
       '호박고구마', '완도김', '공기정화식물', '에어프라이어', '닥터관절치료기', '오곡누룽지', 'TNGT',
       '래쉬톡원터치속눈썹', '재첩국', '보랄블랜더', '손질왕꼬막', '현대손질갈치', '와이엠마스크', '메가비타',
       '생줄랑', '제주한라봉', '셀럽염색제', '병천순대국', 'am인덕션', '끌레르드비쥬', '통뼈감자탕',
       '때르미오', '실리만', '블렌더', '아테스토니쿠션', '잭필드', 'CJ 비비고', '셀리턴LED마스크',
       '드럼쿡', '김영근칼국수', '대저토마토', '오행자금동전파스', '텀블러거품기', '마르조', '다농이네사과',
       '예쎄패션', '오가닉브라', '신일미니밥솥', '클린샷욕실세정제', '깨끗한나라화장지', '이종임 갈비탕',
       '에스콰이아', '양배추진액', '헤어맥스', '행주티슈', '임화자육포', '스테파노콘티', '마음심은곱창',
       '소화기', '패리스힐튼', '지베르니', '안마기', '규조토벽지', '손소독제', '선글라스', '브루스필드',
       '앤클라인', '대구탕', '해남고구마', '광동유산균', '손질새꼬막', '코코젤리다지기', '스와로브스키',
       '더덕무침', 'EM탈취제', '손질 토막갈치', '이종임곰탕', '원터치 싱크선반', '논슬립 옷걸이', '엑스런',
       '김영근명인도토리묵', '썬키스트 오렌지', '국내산고구마', '발락마사지', '몽펠리에', '피톤치오편백오일수',
       '통돌이오븐', '위트24쿠션', '반야월뒷고기', '도어락', '국내산참조기', '태국망고', '엘지통돌이세탁기',
       'SOUP패션', '노르웨이고등어', '국내산피꼬막', '터치앤터치 선반', '랍스타', '끌레드벨리프팅팩',
       '코코젤리', '콜라겐', '고수록모시떡', '강원도더덕', '탄다', '자이글', '나인닷 런닝머신', '이종임김치',
       '하루견과', '카매트', '해뜰찬김치', '주원산 훈제오리', '기절이불', '세척사과', '프로스펙스 속옷',
       '닥터워터전해수', '선스틱', '장어구이', '식기건조대', '자미에슨', '큐브초음파세척기', '반건조오징어',
       '베지밀', '도깨비믹서기', '베베풋', '성주참외', '리리코스팩트', '선식', '그릴', '도깨비에어슬림',
       '거문도', '광천김', '국내산고등어', '엔엔에프 팬츠', '신일믹서기', '로젠침대', '종이호일',
       '셀레뷰립스틱', '에레키반자석패치', '신일', '지베르니1', '닥터웰무선안마기', '차콜풋샴푸', '비즈베개',
       '반건조가자미', '블룸베르크', '멍게', '민물장어', '모공관리기', '다시팩', '사조연어', '다시마국수',
       '마스크팩', '강순의약밥', '진한부대찌개', '아놀드파마', '자연감성속옷', '소노비', 'w클라우드',
       '제주오메기떡', '벤트리', '음파진동기', '할리마리', '스케쳐스', '국수', '제스프리키위', '로질리',
       '반건조우럭', '지나송', '보디가드', '가자미', '예작', '라비오뜨마스크팩', '인덕션', '밀페용기',
       '베개', '르젠서큘레이터', '블롬베르크의류건조기', '손질오징어', '헨리코튼', '공간아트건조대',
       '지니어스채칼', '이숙꽃게', '한스데코커튼', '옥수수', '서산쌀', '제주감귤', '이정섭오리',
       '듀얼바이탈이뮨', '레비노블양우산', '두씽매트', '갓김치', '바다장어', '기삼전복', '조미김',
       '라텍스매트리스', '자연감성의류', '양평해장국', '코브라유니건', '이종임삼계탕', '손질청어', '페인티비',
       '밀라숀', '레져타임', '마스크', '로티캠프', '벤호건', '에스따르염색제', '자두', '어바웃타임',
       '한복선보양탕', '역전회관불고기', '녹십자혈당계', '양희경낙지', '한우곰탕', '에어프랜드', '위생용품',
       '제주단호박', '랭킹닭컴', '텐트', '루나코어스', '파워크레인 킹콩', '복숭아', '마데카', '키플링',
       '제주흑돼지', '위케어마스크', '타트체리', '문어', '레드비트', '면도기', '스텐밀폐용기', '하늘청감주',
       '친정엄마주스', '제주흑돼지구이', '고구마말랭이', '예초기', '손질꽃게'], dtype=object)

In [74]:
no

              날짜     시간             상품명                방송일시  노출(분) 상품군
356   2020-01-05  00:20        제니하우스염색제 2020-01-05 00:20:00   60.0  미정
357   2020-01-10  00:20            브루마스 2020-01-10 00:20:00   60.0  미정
358   2020-01-11  01:20           어성초샴푸 2020-01-11 01:20:00   40.0  미정
359   2020-01-14  01:20             속눈썹 2020-01-14 01:20:00   40.0  미정
360   2020-01-16  01:20             팔레오 2020-01-16 01:20:00   40.0  미정
...          ...    ...             ...                 ...    ...  ..
4658  2020-08-16  13:20            명품잡화 2020-08-16 13:20:00   60.0  미정
4659  2020-08-16  14:20             선풍기 2020-08-16 14:20:00   60.0  미정
4660  2020-08-17  08:20         제주수산물세트 2020-08-17 08:20:00   60.0  미정
4661  2020-08-17  14:20  비버리힐스폴로 남성기초세트 2020-08-17 14:20:00   60.0  미정
4662  2020-08-17  18:20            타트체리 2020-08-17 18:20:00   60.0  미정

[1150 rows x 6 columns]

In [41]:
health_extra = ['녹용','팔팔','팔레오','큐텐','루테인','보스웰리아','비타','배즙','바이오','진액','자미에슨',
                '타트체리','레드비트']

In [42]:
kitchen_extra = ['음식물','참소쿠리','선반','쉐프','블랜더','블렌더','믹서기','거품기','밥솥','드립커피','코코젤리',
                '자이글','홈세트','호일','채칼','듀얼바이탈이뮨','유기세트','인덕션']

In [43]:
stuff_extra = ['슈즈','브루마스','조이앤피스','잡화','마리아','트래커메이트','에스콰이아','스테파노콘티',
              '앤클라인','스와로브스키','소노비','w클라우드','스케쳐스','로티캠프','벤호건','텐트','끌레르드비쥬'
              ,'키플링','우산','보디가드']

In [44]:
furniture_extra = ['벤트리']

In [45]:
appliances_extra = ['비트젯']

In [46]:
food_extra = ['통영','고구마','망고', '갈치','조기','수산물','메주','반찬','만두','사과','레드향','떡',
             '한우','미역','옥돔','완도','식물','누룽지','한라봉','순대','칼국수','토마토','육포','양념',
             '더덕','참조기','도토리','오렌지','뒷고기','고등어','랍스타','더덕','견과','오리','참외',
             '선식','거문도','광천김','가자미','멍게','다시팩','연어','국수','밥','찌개','떡','키위','우럭',
             '풍년','제주','옥수수','조미김','해장국','청어','손질','자두','불고기','랭킹닭컴','복숭아',
              '하늘청감주','주스','흙돼지','비비고']

In [75]:
underwear_extra = ['브라','속옷','팬티','드로즈']

In [77]:
life_extra = ['아이러브허브','세제','클리너','견인기','밸런스핏','에어로팡팡','유연제','치료기',
             '동전','화장지','다리미','소화기','안마기','손소독제','탈취제','마사지','오일수','옷걸이','엑스런',
             '탄다','전해수','매트','세척기','베베풋','에어슬림','음파','건조대',
             '팻밀리아','코브라유니건','페인티비','구강','녹십자혈당계','에어프랜드','위생용품',
             '폴리처커버세트','파워크레인','때르미오','신일','배개','배게','베개','비데','폴딩선반','보국',
             '서큘레이터','르젠서큘레이터','선풍기','블룸베르크']

In [78]:
hairdressing_extra = ['기초','염색제','샴푸','속눈썹','비누','헤어','트리트먼트','가발','바비리스','패리스힐튼',
                     '쿠션','끌레드벨리프팅팩','팩트','모공','파마','마데카','면도기','치약','칫솔','칫솔살균기']

In [79]:
bedding_extra =['이불','커튼','지나송']

In [80]:
cloth_extra = ['패션','TNGT','마르조','지베르니','브루스필드','몽펠리에','지베르니','할리마리','로질리',
              '예작','헨리코튼','의류','밀라숀','레져타임','어바웃타임','루나코어스','잭필드']

In [82]:
product = []
for i in range(len(no)):
    if any(x in no.iloc[i][2] for x in life_extra):
        product.append('생활용품')
    elif any(x in no.iloc[i][2] for x in cloth_extra):
        product.append('의류')
#     elif any(x in no.iloc[i][2] for x in mu_extra):
#         product.append('무형')
    elif any(x in no.iloc[i][2] for x in kitchen_extra):
        product.append('주방')
    elif any(x in no.iloc[i][2] for x in stuff_extra):
        product.append('잡화')        
    elif any(x in no.iloc[i][2] for x in furniture_extra):
        product.append('가구')        
    elif any(x in no.iloc[i][2] for x in appliances_extra):
        product.append('가전')
    elif any(x in no.iloc[i][2] for x in underwear_extra):
        product.append('속옷')
    elif any(x in no.iloc[i][2] for x in hairdressing_extra):
        product.append('이미용')        
    elif any(x in no.iloc[i][2] for x in bedding_extra):
        product.append('침구')        
    elif any(x in no.iloc[i][2] for x in health_extra):
        product.append('건강기능')        
    elif any(x in no.iloc[i][2] for x in food_extra):
        product.append('농수축')        
    else:
        product.append('미정')

In [83]:
no['상품군'] = product

C:\Users\YOO\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [84]:
no

              날짜     시간             상품명                방송일시  노출(분)   상품군
356   2020-01-05  00:20        제니하우스염색제 2020-01-05 00:20:00   60.0   이미용
357   2020-01-10  00:20            브루마스 2020-01-10 00:20:00   60.0    잡화
358   2020-01-11  01:20           어성초샴푸 2020-01-11 01:20:00   40.0   이미용
359   2020-01-14  01:20             속눈썹 2020-01-14 01:20:00   40.0   이미용
360   2020-01-16  01:20             팔레오 2020-01-16 01:20:00   40.0  건강기능
...          ...    ...             ...                 ...    ...   ...
4658  2020-08-16  13:20            명품잡화 2020-08-16 13:20:00   60.0    잡화
4659  2020-08-16  14:20             선풍기 2020-08-16 14:20:00   60.0  생활용품
4660  2020-08-17  08:20         제주수산물세트 2020-08-17 08:20:00   60.0   농수축
4661  2020-08-17  14:20  비버리힐스폴로 남성기초세트 2020-08-17 14:20:00   60.0   이미용
4662  2020-08-17  18:20            타트체리 2020-08-17 18:20:00   60.0  건강기능

[1150 rows x 6 columns]

In [85]:
data_time = pd.concat([complete,no],ignore_index = True)
data_time

              날짜     시간             상품명                방송일시  노출(분)   상품군
0     2020-01-01  00:20            삼성화재 2020-01-01 00:20:00   60.0    무형
1     2020-01-01  01:20           예다함상조 2020-01-01 01:20:00   40.0    무형
2     2020-01-02  00:20       DB운전자보험2부 2020-01-02 00:20:00   60.0    무형
3     2020-01-02  01:20          헤스티지패션 2020-01-02 01:20:00   40.0    의류
4     2020-01-03  00:20          프리드라이프 2020-01-03 00:20:00   60.0    무형
...          ...    ...             ...                 ...    ...   ...
4658  2020-08-16  13:20            명품잡화 2020-08-16 13:20:00   60.0    잡화
4659  2020-08-16  14:20             선풍기 2020-08-16 14:20:00   60.0  생활용품
4660  2020-08-17  08:20         제주수산물세트 2020-08-17 08:20:00   60.0   농수축
4661  2020-08-17  14:20  비버리힐스폴로 남성기초세트 2020-08-17 14:20:00   60.0   이미용
4662  2020-08-17  18:20            타트체리 2020-08-17 18:20:00   60.0  건강기능

[4663 rows x 6 columns]

In [86]:
data_time['상품군'].unique()

array(['무형', '의류', '이미용', '농수축', '가구', '속옷', '가전', '생활용품', '잡화', '주방',
       '건강기능', '침구'], dtype=object)

In [87]:
data_time10 = data_time[data_time['시간'] < '02:00']
data_time11 = data_time[data_time['시간'] > '06:00']

In [88]:
data_time = pd.concat([data_time10,data_time11],ignore_index = True)
data_time

              날짜     시간             상품명                방송일시  노출(분)   상품군
0     2020-01-01  00:20            삼성화재 2020-01-01 00:20:00   60.0    무형
1     2020-01-01  01:20           예다함상조 2020-01-01 01:20:00   40.0    무형
2     2020-01-02  00:20       DB운전자보험2부 2020-01-02 00:20:00   60.0    무형
3     2020-01-02  01:20          헤스티지패션 2020-01-02 01:20:00   40.0    의류
4     2020-01-03  00:20          프리드라이프 2020-01-03 00:20:00   60.0    무형
...          ...    ...             ...                 ...    ...   ...
4658  2020-08-16  13:20            명품잡화 2020-08-16 13:20:00   60.0    잡화
4659  2020-08-16  14:20             선풍기 2020-08-16 14:20:00   60.0  생활용품
4660  2020-08-17  08:20         제주수산물세트 2020-08-17 08:20:00   60.0   농수축
4661  2020-08-17  14:20  비버리힐스폴로 남성기초세트 2020-08-17 14:20:00   60.0   이미용
4662  2020-08-17  18:20            타트체리 2020-08-17 18:20:00   60.0  건강기능

[4663 rows x 6 columns]

In [89]:
data_time['방송일시'] = pd.to_datetime(data_time['방송일시'])
data_time2 = data_time.sort_values(by='방송일시').reset_index(drop=True)

In [90]:
data_time2 = data_time2[['방송일시','노출(분)','상품명','상품군','날짜','시간']]

In [91]:
data_time2['방송월'] = data_time2['방송일시'].dt.month 
data_time2['방송요일'] = data_time2['방송일시'].dt.dayofweek

In [92]:
#무형 제거
# data_time2 = data_time2[data_time2['상품군'] != '무형']

In [93]:
data_time2

                    방송일시  노출(분)      상품명   상품군          날짜     시간  방송월  방송요일
0    2020-01-01 00:20:00   60.0     삼성화재    무형  2020-01-01  00:20    1     2
1    2020-01-01 01:20:00   40.0    예다함상조    무형  2020-01-01  01:20    1     2
2    2020-01-01 06:20:00   60.0     굿프렌드  생활용품  2020-01-01  06:20    1     2
3    2020-01-01 07:20:00   60.0  마르엘라로사티    의류  2020-01-01  07:20    1     2
4    2020-01-01 08:20:00   60.0      오델로    잡화  2020-01-01  08:20    1     2
...                  ...    ...      ...   ...         ...    ...  ...   ...
4658 2020-08-17 19:20:00   60.0   헤드남자속옷    속옷  2020-08-17  19:20    8     0
4659 2020-08-17 20:20:00   60.0      예초기  생활용품  2020-08-17  20:20    8     0
4660 2020-08-17 21:20:00   60.0    LG냉장고    가전  2020-08-17  21:20    8     0
4661 2020-08-17 22:20:00   60.0     LGTV    가전  2020-08-17  22:20    8     0
4662 2020-08-17 23:20:00    0.0    예다함상조    무형  2020-08-17  23:20    8     0

[4663 rows x 8 columns]

In [94]:
data_time2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4663 entries, 0 to 4662
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   방송일시    4663 non-null   datetime64[ns]
 1   노출(분)   4663 non-null   float64
 2   상품명     4663 non-null   object
 3   상품군     4663 non-null   object
 4   날짜      4663 non-null   object
 5   시간      4663 non-null   object
 6   방송월     4663 non-null   int64
 7   방송요일    4663 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 291.6+ KB

In [95]:
data_time2.head(30)

,방송일시,노출(분),상품명,상품군,날짜,시간,방송월,방송요일
0,2020-01-01 00:20:00,60.0,삼성화재,무형,2020-01-01,00:20,1,2
1,2020-01-01 01:20:00,40.0,예다함상조,무형,2020-01-01,01:20,1,2
2,2020-01-01 06:20:00,60.0,굿프렌드,생활용품,2020-01-01,06:20,1,2
3,2020-01-01 07:20:00,60.0,마르엘라로사티,의류,2020-01-01,07:20,1,2
4,2020-01-01 08:20:00,60.0,오델로,잡화,2020-01-01,08:20,1,2
5,2020-01-01 09:20:00,60.0,보닌남성기초,이미용,2020-01-01,09:20,1,2
6,2020-01-01 10:20:00,60.0,헤스티지 재킷,의류,2020-01-01,10:20,1,2
7,2020-01-01 11:20:00,60.0,코치,잡화,2020-01-01,11:20,1,2
8,2020-01-01 12:20:00,60.0,DB운전자보험,무형,2020-01-01,12:20,1,2
9,2020-01-01 13:20:00,60.0,레이프릴속옷,속옷,2020-01-01,13:20,1,2
10,2020-01-01 14:20:00,60.0,참존,이미용,2020-01-01,14:20,1,2
11,2020-01-01 15:20:00,60.0,램프쿡,주방,2020-01-01,15:20,1,2
12,2020-01-01 16:20:00,60.0,도가니탕,농수축,2020-01-01,16:20,1,2
13,2020-01-01 17:20:00,60.0,손질갑오징어,농수축,2020-01-01,17:20,1,2
14,2020-01-01 18:20:00,60.0,쿠첸전기밥솥,주방,2020-01-01,18:20,1,2
15,2020-01-01 19:20:00,60.0,푸마드로즈,속옷,2020-01-01,19:20,1,2
16,2020-01-01 20:20:00,60.0,현대정수기,무형,2020-01-01,20:20,1,2
17,2020-01-01 21:20:00,60.0,LGTV,가전,2020-01-01,21:20,1,2
18,2020-01-01 22:20:00,60.0,장수흙침대,가구,2020-01-01,22:20,1,2
19,2020-01-01 23:20:00,60.0,비버리힐스폴로 남성기초세트,이미용,2020-01-01,23:20,1,2
20,2020-01-02 00:20:00,60.0,DB운전자보험2부,무형,2020-01-02,00:20,1,3
21,2020-01-02 01:20:00,40.0,헤스티지패션,의류,2020-01-02,01:20,1,3
22,2020-01-02 06:20:00,60.0,아이러브허브,생활용품,2020-01-02,06:20,1,3
23,2020-01-02 07:20:00,60.0,브루마스,잡화,2020-01-02,07:20,1,3
24,2020-01-02 08:20:00,60.0,네오젠,이미용,2020-01-02,08:20,1,3
25,2020-01-02 09:20:00,60.0,IH가마솥,주방,2020-01-02,09:20,1,3
26,2020-01-02 10:20:00,60.0,영산포 숙성 홍어회,농수축,2020-01-02,10:20,1,3
27,2020-01-02 11:20:00,60.0,오세득갈비탕,농수축,2020-01-02,11:20,1,3
28,2020-01-02 12:20:00,60.0,암블로슈즈,잡화,2020-01-02,12:20,1,3
29,2020-01-02 13:20:00,60.0,음식물처리기,무형,2020-01-02,13:20,1,3

In [97]:
import pandas as pd
data_time2.to_csv('data/pairing.csv', encoding='utf-8-sig', index=False)